"""Configuration catalogue for Bharati Environment Observations (87 Points).

Part of SIH 2026 Project SIH26060: F.R.I.D.A.Y.
Digital Platform for Efficient Remote Management of Indian Antarctic Research Stations.

NOTE: 87 simulated environmental telemetry points configured for the Bharati digital-twin prototype.
Not claimed to be physically installed at Bharati unless classified as DOCUMENTED.
"""

from __future__ import annotations

from .models import (
    EnvironmentDomain,
    EvidenceLevel,
    PhysicalQuantity,
    SensorConfig,
    SensorKind,
)

SOURCE_REFERENCE_DEFAULT: str = "bharati_environment_physics_v1"

# Deterministic evidence baseline confidence levels
CONFIDENCE_BASELINE: dict[EvidenceLevel, float] = {
    EvidenceLevel.DOCUMENTED: 1.00,
    EvidenceLevel.IMPLIED: 0.90,
    EvidenceLevel.DERIVED: 0.85,
    EvidenceLevel.NOT_PUBLICLY_CONFIRMED: 0.75,
}


def get_confidence_for_evidence(evidence: EvidenceLevel) -> float:
    """Return deterministic confidence score based on evidence classification."""
    return CONFIDENCE_BASELINE.get(evidence, 0.70)


ENVIRONMENT_SENSOR_CONFIGS: dict[str, SensorConfig] = {
    # =========================================================================
    # DOMAIN 1: WEATHER / METEOROLOGY (12 Sensors)
    # =========================================================================
    "ENV-WX-TEMP": SensorConfig(
        sensor_id="ENV-WX-TEMP",
        name="Ambient Air Temperature",
        asset_id="WEATHER_STATION",
        domain=EnvironmentDomain.WEATHER,
        subsystem="SURFACE_MET",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.DOCUMENTED,
        physical_quantity=PhysicalQuantity.TEMPERATURE,
        unit="degC",
        sampling_interval_seconds=10.0,
        min_value=-50.0,
        max_value=15.0,
        default_value=-18.0,
        state_path="weather.ambient_temperature_c",
        description="Ambient air temperature measured at meteorological mast (AWS).",
    ),
    "ENV-WX-RH": SensorConfig(
        sensor_id="ENV-WX-RH",
        name="Ambient Relative Humidity",
        asset_id="WEATHER_STATION",
        domain=EnvironmentDomain.WEATHER,
        subsystem="SURFACE_MET",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.DOCUMENTED,
        physical_quantity=PhysicalQuantity.RELATIVE_HUMIDITY,
        unit="%",
        sampling_interval_seconds=10.0,
        min_value=0.0,
        max_value=100.0,
        default_value=65.0,
        state_path="weather.relative_humidity_percent",
        description="Ambient relative humidity from capacitive hygrometer.",
    ),
    "ENV-WX-PRESS": SensorConfig(
        sensor_id="ENV-WX-PRESS",
        name="Atmospheric Barometric Pressure",
        asset_id="WEATHER_STATION",
        domain=EnvironmentDomain.WEATHER,
        subsystem="SURFACE_MET",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.DOCUMENTED,
        physical_quantity=PhysicalQuantity.PRESSURE,
        unit="hPa",
        sampling_interval_seconds=10.0,
        min_value=920.0,
        max_value=1040.0,
        default_value=985.0,
        state_path="weather.atmospheric_pressure_hpa",
        description="Barometric atmospheric sea-level equivalent pressure.",
    ),
    "ENV-WX-PRESS-TEND": SensorConfig(
        sensor_id="ENV-WX-PRESS-TEND",
        name="3-Hour Barometric Pressure Tendency",
        asset_id="WEATHER_STATION",
        domain=EnvironmentDomain.WEATHER,
        subsystem="SURFACE_MET",
        kind=SensorKind.DERIVED,
        evidence_level=EvidenceLevel.DERIVED,
        physical_quantity=PhysicalQuantity.PRESSURE_TENDENCY,
        unit="hPa_3h",
        sampling_interval_seconds=10.0,
        min_value=-25.0,
        max_value=25.0,
        default_value=-0.2,
        state_path="weather.pressure_tendency_hpa_3h",
        state_dependencies=["weather.atmospheric_pressure_hpa"],
        description="3-hour atmospheric pressure tendency (rate of change dP/3h).",
    ),
    "ENV-WX-WIND-S": SensorConfig(
        sensor_id="ENV-WX-WIND-S",
        name="Sustained Wind Speed",
        asset_id="WEATHER_STATION",
        domain=EnvironmentDomain.WEATHER,
        subsystem="SURFACE_MET",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.DOCUMENTED,
        physical_quantity=PhysicalQuantity.WIND_SPEED,
        unit="m_s",
        sampling_interval_seconds=5.0,
        min_value=0.0,
        max_value=65.0,
        default_value=12.0,
        state_path="weather.wind_speed_mps",
        description="10m mast ultrasonic/cup sustained wind speed.",
    ),
    "ENV-WX-WIND-D": SensorConfig(
        sensor_id="ENV-WX-WIND-D",
        name="Wind Direction",
        asset_id="WEATHER_STATION",
        domain=EnvironmentDomain.WEATHER,
        subsystem="SURFACE_MET",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.DOCUMENTED,
        physical_quantity=PhysicalQuantity.DIRECTION,
        unit="deg",
        sampling_interval_seconds=5.0,
        min_value=0.0,
        max_value=360.0,
        default_value=85.0,
        state_path="weather.wind_direction_deg",
        description="Wind direction in degrees from true North.",
    ),
    "ENV-WX-GUST": SensorConfig(
        sensor_id="ENV-WX-GUST",
        name="Peak Wind Gust Speed",
        asset_id="WEATHER_STATION",
        domain=EnvironmentDomain.WEATHER,
        subsystem="SURFACE_MET",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.IMPLIED,
        physical_quantity=PhysicalQuantity.WIND_SPEED,
        unit="m_s",
        sampling_interval_seconds=5.0,
        min_value=0.0,
        max_value=85.0,
        default_value=16.5,
        state_path="weather.wind_gust_mps",
        description="Peak 3-second wind gust velocity.",
    ),
    "ENV-WX-GUST-D": SensorConfig(
        sensor_id="ENV-WX-GUST-D",
        name="Peak Wind Gust Direction",
        asset_id="WEATHER_STATION",
        domain=EnvironmentDomain.WEATHER,
        subsystem="SURFACE_MET",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.IMPLIED,
        physical_quantity=PhysicalQuantity.DIRECTION,
        unit="deg",
        sampling_interval_seconds=5.0,
        min_value=0.0,
        max_value=360.0,
        default_value=85.0,
        state_path="weather.wind_gust_direction_deg",
        description="Direction of peak wind gust in degrees.",
    ),
    "ENV-WX-VIS": SensorConfig(
        sensor_id="ENV-WX-VIS",
        name="Horizontal Atmospheric Visibility",
        asset_id="WEATHER_STATION",
        domain=EnvironmentDomain.WEATHER,
        subsystem="SURFACE_MET",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.NOT_PUBLICLY_CONFIRMED,
        physical_quantity=PhysicalQuantity.DISTANCE,
        unit="m",
        sampling_interval_seconds=10.0,
        min_value=10.0,
        max_value=50000.0,
        default_value=15000.0,
        state_path="weather.visibility_m",
        description="Meteorological optical range horizontal visibility.",
    ),
    "ENV-WX-PRECIP-RATE": SensorConfig(
        sensor_id="ENV-WX-PRECIP-RATE",
        name="Precipitation Water-Equivalent Rate",
        asset_id="WEATHER_STATION",
        domain=EnvironmentDomain.WEATHER,
        subsystem="SURFACE_MET",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.IMPLIED,
        physical_quantity=PhysicalQuantity.RATE,
        unit="mm_h",
        sampling_interval_seconds=10.0,
        min_value=0.0,
        max_value=40.0,
        default_value=0.5,
        state_path="weather.precipitation_rate_mm_h",
        description="Liquid-water-equivalent precipitation / snowfall rate.",
    ),
    "ENV-WX-DEW": SensorConfig(
        sensor_id="ENV-WX-DEW",
        name="Dew Point Temperature",
        asset_id="WEATHER_STATION",
        domain=EnvironmentDomain.WEATHER,
        subsystem="SURFACE_MET",
        kind=SensorKind.DERIVED,
        evidence_level=EvidenceLevel.DERIVED,
        physical_quantity=PhysicalQuantity.TEMPERATURE,
        unit="degC",
        sampling_interval_seconds=10.0,
        min_value=-60.0,
        max_value=15.0,
        default_value=-22.5,
        state_path="weather.dew_point_c",
        state_dependencies=["weather.ambient_temperature_c", "weather.relative_humidity_percent"],
        description="Dew point computed deterministically via Magnus-Tetens formula.",
    ),
    "ENV-WX-DENS": SensorConfig(
        sensor_id="ENV-WX-DENS",
        name="Moist Air Density",
        asset_id="WEATHER_STATION",
        domain=EnvironmentDomain.WEATHER,
        subsystem="SURFACE_MET",
        kind=SensorKind.DERIVED,
        evidence_level=EvidenceLevel.DERIVED,
        physical_quantity=PhysicalQuantity.MASS_CONCENTRATION,
        unit="kg_m3",
        sampling_interval_seconds=10.0,
        min_value=0.9,
        max_value=1.6,
        default_value=1.34,
        state_path="weather.air_density_kg_m3",
        state_dependencies=["weather.atmospheric_pressure_hpa", "weather.ambient_temperature_c", "weather.relative_humidity_percent"],
        description="Moist air density calculated from CIPM ideal gas formulation.",
    ),

    # =========================================================================
    # DOMAIN 2: RADIATION & ATMOSPHERIC OPTICS (7 Sensors)
    # =========================================================================
    "ENV-RAD-SW": SensorConfig(
        sensor_id="ENV-RAD-SW",
        name="Downwelling Shortwave Solar Radiation",
        asset_id="RADIATION_STATION",
        domain=EnvironmentDomain.RADIATION,
        subsystem="SOLAR_RAD",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.DOCUMENTED,
        physical_quantity=PhysicalQuantity.SOLAR_IRRADIANCE,
        unit="W_m2",
        sampling_interval_seconds=10.0,
        min_value=0.0,
        max_value=1200.0,
        default_value=150.0,
        state_path="radiation.shortwave_downwelling_w_m2",
        description="Global horizontal downwelling solar irradiance from Pyranometer.",
    ),
    "ENV-RAD-LW": SensorConfig(
        sensor_id="ENV-RAD-LW",
        name="Downwelling Longwave Atmospheric Radiation",
        asset_id="RADIATION_STATION",
        domain=EnvironmentDomain.RADIATION,
        subsystem="SOLAR_RAD",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.IMPLIED,
        physical_quantity=PhysicalQuantity.SOLAR_IRRADIANCE,
        unit="W_m2",
        sampling_interval_seconds=10.0,
        min_value=50.0,
        max_value=450.0,
        default_value=210.0,
        state_path="radiation.longwave_downwelling_w_m2",
        description="Downward thermal infrared radiation from Pyrgeometer.",
    ),
    "ENV-RAD-NET": SensorConfig(
        sensor_id="ENV-RAD-NET",
        name="Net All-Wave Radiation",
        asset_id="RADIATION_STATION",
        domain=EnvironmentDomain.RADIATION,
        subsystem="SOLAR_RAD",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.IMPLIED,
        physical_quantity=PhysicalQuantity.SOLAR_IRRADIANCE,
        unit="W_m2",
        sampling_interval_seconds=10.0,
        min_value=-150.0,
        max_value=500.0,
        default_value=-25.0,
        state_path="radiation.net_radiation_w_m2",
        description="Net all-wave radiation balance (downwelling - upwelling).",
    ),
    "ENV-RAD-UV": SensorConfig(
        sensor_id="ENV-RAD-UV",
        name="Solar Ultraviolet Index",
        asset_id="RADIATION_STATION",
        domain=EnvironmentDomain.RADIATION,
        subsystem="SOLAR_RAD",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.DOCUMENTED,
        physical_quantity=PhysicalQuantity.INDEX,
        unit="score",
        sampling_interval_seconds=10.0,
        min_value=0.0,
        max_value=16.0,
        default_value=2.0,
        state_path="radiation.uv_index",
        description="Solar UV index from spectrophotometer/UV radiometer.",
    ),
    "ENV-RAD-AOD": SensorConfig(
        sensor_id="ENV-RAD-AOD",
        name="Aerosol Optical Depth at 500nm",
        asset_id="ATMOSPHERIC_OPTICS",
        domain=EnvironmentDomain.RADIATION,
        subsystem="ATM_OPTICS",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.DOCUMENTED,
        physical_quantity=PhysicalQuantity.OPTICAL_DEPTH,
        unit="ratio",
        sampling_interval_seconds=30.0,
        min_value=0.0,
        max_value=1.5,
        default_value=0.035,
        state_path="radiation.aerosol_optical_depth_500nm",
        description="Aerosol optical depth at 500nm from Microtops sunphotometer.",
    ),
    "ENV-RAD-DAYLIGHT": SensorConfig(
        sensor_id="ENV-RAD-DAYLIGHT",
        name="Polar Daylight State",
        asset_id="RADIATION_STATION",
        domain=EnvironmentDomain.RADIATION,
        subsystem="SOLAR_RAD",
        kind=SensorKind.STATE,
        evidence_level=EvidenceLevel.IMPLIED,
        physical_quantity=PhysicalQuantity.PRESENCE,
        unit="bool",
        sampling_interval_seconds=10.0,
        default_value=True,
        state_path="radiation.is_daylight",
        description="Astronomical solar illumination state (True=daylight, False=night).",
    ),
    "ENV-RAD-SOLAR-AVAIL": SensorConfig(
        sensor_id="ENV-RAD-SOLAR-AVAIL",
        name="Solar Energy Availability Factor",
        asset_id="RADIATION_STATION",
        domain=EnvironmentDomain.RADIATION,
        subsystem="SOLAR_RAD",
        kind=SensorKind.DERIVED,
        evidence_level=EvidenceLevel.DERIVED,
        physical_quantity=PhysicalQuantity.PERCENT,
        unit="%",
        sampling_interval_seconds=10.0,
        min_value=0.0,
        max_value=100.0,
        default_value=25.0,
        state_path="radiation.solar_availability_percent",
        state_dependencies=["radiation.shortwave_downwelling_w_m2", "radiation.is_daylight"],
        description="Normalized percentage of solar energy generation potential.",
    ),

    # =========================================================================
    # DOMAIN 3: ATMOSPHERIC AEROSOL & AIR QUALITY (12 Sensors)
    # =========================================================================
    "ENV-AIR-BC": SensorConfig(
        sensor_id="ENV-AIR-BC",
        name="Black Carbon Mass Concentration",
        asset_id="AEROSOL_LAB",
        domain=EnvironmentDomain.ATMOSPHERIC_AEROSOL,
        subsystem="AEROSOL",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.DOCUMENTED,
        physical_quantity=PhysicalQuantity.MASS_CONCENTRATION,
        unit="ng_m3",
        sampling_interval_seconds=30.0,
        min_value=0.0,
        max_value=2000.0,
        default_value=15.0,
        state_path="aerosol.black_carbon_ng_m3",
        description="Aethalometer AE-31/33 equivalent black carbon mass concentration.",
    ),
    "ENV-AIR-AERO": SensorConfig(
        sensor_id="ENV-AIR-AERO",
        name="Aerosol Mass Concentration PM10",
        asset_id="AEROSOL_LAB",
        domain=EnvironmentDomain.ATMOSPHERIC_AEROSOL,
        subsystem="AEROSOL",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.DOCUMENTED,
        physical_quantity=PhysicalQuantity.MASS_CONCENTRATION,
        unit="ug_m3",
        sampling_interval_seconds=30.0,
        min_value=0.0,
        max_value=150.0,
        default_value=3.5,
        state_path="aerosol.pm10_ug_m3",
        description="PM10 coarse aerosol particulate mass concentration.",
    ),
    "ENV-AIR-PCOUNT": SensorConfig(
        sensor_id="ENV-AIR-PCOUNT",
        name="Total Aerosol Particle Number Concentration",
        asset_id="AEROSOL_LAB",
        domain=EnvironmentDomain.ATMOSPHERIC_AEROSOL,
        subsystem="AEROSOL",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.DOCUMENTED,
        physical_quantity=PhysicalQuantity.PARTICLE_COUNT,
        unit="1_cm3",
        sampling_interval_seconds=10.0,
        min_value=0.0,
        max_value=20000.0,
        default_value=450.0,
        state_path="aerosol.particle_number_cm3",
        description="Condensation Particle Counter total aerosol particle number density.",
    ),
    "ENV-AIR-PSIZE": SensorConfig(
        sensor_id="ENV-AIR-PSIZE",
        name="Geometric Mean Particle Diameter",
        asset_id="AEROSOL_LAB",
        domain=EnvironmentDomain.ATMOSPHERIC_AEROSOL,
        subsystem="AEROSOL",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.IMPLIED,
        physical_quantity=PhysicalQuantity.DEPTH,
        unit="nm",
        sampling_interval_seconds=30.0,
        min_value=1.0,
        max_value=1000.0,
        default_value=65.0,
        state_path="aerosol.mean_particle_size_nm",
        description="Mobility particle sizer geometric mean diameter.",
    ),
    "ENV-AIR-SCAT": SensorConfig(
        sensor_id="ENV-AIR-SCAT",
        name="Aerosol Light Scattering Coefficient at 550nm",
        asset_id="AEROSOL_LAB",
        domain=EnvironmentDomain.ATMOSPHERIC_AEROSOL,
        subsystem="AEROSOL",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.DOCUMENTED,
        physical_quantity=PhysicalQuantity.SCATTERING_COEFFICIENT,
        unit="1_Mm",
        sampling_interval_seconds=30.0,
        min_value=0.0,
        max_value=50.0,
        default_value=1.8,
        state_path="aerosol.scattering_coeff_Mm_inv",
        description="Integrating nephelometer light scattering coefficient at 550nm.",
    ),
    "ENV-AIR-ABS": SensorConfig(
        sensor_id="ENV-AIR-ABS",
        name="Aerosol Light Absorption Coefficient at 880nm",
        asset_id="AEROSOL_LAB",
        domain=EnvironmentDomain.ATMOSPHERIC_AEROSOL,
        subsystem="AEROSOL",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.DOCUMENTED,
        physical_quantity=PhysicalQuantity.ABSORPTION_COEFFICIENT,
        unit="1_Mm",
        sampling_interval_seconds=30.0,
        min_value=0.0,
        max_value=20.0,
        default_value=0.12,
        state_path="aerosol.absorption_coeff_Mm_inv",
        description="Aethalometer aerosol light absorption coefficient at 880nm.",
    ),
    "ENV-AIR-AOD": SensorConfig(
        sensor_id="ENV-AIR-AOD",
        name="Column Integrated Aerosol Optical Depth",
        asset_id="AEROSOL_LAB",
        domain=EnvironmentDomain.ATMOSPHERIC_AEROSOL,
        subsystem="AEROSOL",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.DOCUMENTED,
        physical_quantity=PhysicalQuantity.OPTICAL_DEPTH,
        unit="ratio",
        sampling_interval_seconds=30.0,
        min_value=0.0,
        max_value=1.0,
        default_value=0.032,
        state_path="aerosol.column_aod",
        description="Total atmospheric column aerosol optical depth.",
    ),
    "ENV-AIR-CO": SensorConfig(
        sensor_id="ENV-AIR-CO",
        name="Carbon Monoxide Concentration",
        asset_id="AIR_QUALITY_MONITOR",
        domain=EnvironmentDomain.ATMOSPHERIC_AEROSOL,
        subsystem="TRACE_GAS",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.IMPLIED,
        physical_quantity=PhysicalQuantity.MASS_CONCENTRATION,
        unit="ppb",
        sampling_interval_seconds=30.0,
        min_value=0.0,
        max_value=500.0,
        default_value=45.0,
        state_path="aerosol.carbon_monoxide_ppb",
        description="Ambient background and generator plume carbon monoxide.",
    ),
    "ENV-AIR-NOX": SensorConfig(
        sensor_id="ENV-AIR-NOX",
        name="Nitrogen Oxides Concentration",
        asset_id="AIR_QUALITY_MONITOR",
        domain=EnvironmentDomain.ATMOSPHERIC_AEROSOL,
        subsystem="TRACE_GAS",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.IMPLIED,
        physical_quantity=PhysicalQuantity.MASS_CONCENTRATION,
        unit="ppb",
        sampling_interval_seconds=30.0,
        min_value=0.0,
        max_value=100.0,
        default_value=1.2,
        state_path="aerosol.nitrogen_oxides_ppb",
        description="Chemiluminescence NOx (NO + NO2) ambient trace concentration.",
    ),
    "ENV-AIR-SO2": SensorConfig(
        sensor_id="ENV-AIR-SO2",
        name="Sulfur Dioxide Concentration",
        asset_id="AIR_QUALITY_MONITOR",
        domain=EnvironmentDomain.ATMOSPHERIC_AEROSOL,
        subsystem="TRACE_GAS",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.IMPLIED,
        physical_quantity=PhysicalQuantity.MASS_CONCENTRATION,
        unit="ppb",
        sampling_interval_seconds=30.0,
        min_value=0.0,
        max_value=50.0,
        default_value=0.3,
        state_path="aerosol.sulfur_dioxide_ppb",
        description="UV fluorescence SO2 ambient trace gas concentration.",
    ),
    "ENV-AIR-O3": SensorConfig(
        sensor_id="ENV-AIR-O3",
        name="Surface Ozone Concentration",
        asset_id="AIR_QUALITY_MONITOR",
        domain=EnvironmentDomain.ATMOSPHERIC_AEROSOL,
        subsystem="TRACE_GAS",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.NOT_PUBLICLY_CONFIRMED,
        physical_quantity=PhysicalQuantity.MASS_CONCENTRATION,
        unit="ppb",
        sampling_interval_seconds=30.0,
        min_value=0.0,
        max_value=120.0,
        default_value=22.0,
        state_path="aerosol.surface_ozone_ppb",
        description="Surface tropospheric ozone (not confirmed in routine Bharati ops).",
    ),
    "ENV-AIR-QUALITY": SensorConfig(
        sensor_id="ENV-AIR-QUALITY",
        name="Clean Air Baseline Index",
        asset_id="AIR_QUALITY_MONITOR",
        domain=EnvironmentDomain.ATMOSPHERIC_AEROSOL,
        subsystem="AIR_QUALITY",
        kind=SensorKind.DERIVED,
        evidence_level=EvidenceLevel.DERIVED,
        physical_quantity=PhysicalQuantity.INDEX,
        unit="%",
        sampling_interval_seconds=30.0,
        min_value=0.0,
        max_value=100.0,
        default_value=98.0,
        state_path="aerosol.air_quality_index",
        state_dependencies=["aerosol.black_carbon_ng_m3", "aerosol.pm10_ug_m3", "aerosol.carbon_monoxide_ppb", "aerosol.nitrogen_oxides_ppb"],
        description="Antarctic pristine baseline air purity index (100% = pristine).",
    ),

    # =========================================================================
    # DOMAIN 4: SNOW & SEA ICE (11 Sensors)
    # =========================================================================
    # Local Station Snowpack (location_scope="LOCAL_STATION", measurement_zone="STATION_PERIMETER")
    "ENV-SNOW-DEPTH": SensorConfig(
        sensor_id="ENV-SNOW-DEPTH",
        name="Local Snow Cover Depth",
        asset_id="STATION_SNOW_ARRAY",
        domain=EnvironmentDomain.SNOW_ICE,
        subsystem="STATION_SNOW",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.DOCUMENTED,
        physical_quantity=PhysicalQuantity.DEPTH,
        unit="m",
        sampling_interval_seconds=60.0,
        location_scope="LOCAL_STATION",
        measurement_zone="STATION_PERIMETER",
        min_value=0.0,
        max_value=8.0,
        default_value=0.85,
        state_path="snow.snow_depth_m",
        description="Ultrasonic snow depth gauge at station perimeter stake array.",
    ),
    "ENV-SNOW-TEMP": SensorConfig(
        sensor_id="ENV-SNOW-TEMP",
        name="Snowpack Temperature at 20cm",
        asset_id="STATION_SNOW_ARRAY",
        domain=EnvironmentDomain.SNOW_ICE,
        subsystem="STATION_SNOW",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.IMPLIED,
        physical_quantity=PhysicalQuantity.TEMPERATURE,
        unit="degC",
        sampling_interval_seconds=60.0,
        location_scope="LOCAL_STATION",
        measurement_zone="STATION_PERIMETER",
        min_value=-45.0,
        max_value=2.0,
        default_value=-16.0,
        state_path="snow.snow_temperature_c",
        description="Snowpack internal temperature at 20cm depth.",
    ),
    "ENV-SNOW-DENS": SensorConfig(
        sensor_id="ENV-SNOW-DENS",
        name="Snow Bulk Density",
        asset_id="STATION_SNOW_ARRAY",
        domain=EnvironmentDomain.SNOW_ICE,
        subsystem="STATION_SNOW",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.IMPLIED,
        physical_quantity=PhysicalQuantity.MASS_CONCENTRATION,
        unit="kg_m3",
        sampling_interval_seconds=300.0,
        location_scope="LOCAL_STATION",
        measurement_zone="STATION_PERIMETER",
        min_value=100.0,
        max_value=600.0,
        default_value=380.0,
        state_path="snow.snow_density_kg_m3",
        description="Bulk snow density estimated from compaction and core survey.",
    ),
    "ENV-SNOW-ACC": SensorConfig(
        sensor_id="ENV-SNOW-ACC",
        name="Snow Accumulation Rate",
        asset_id="STATION_SNOW_ARRAY",
        domain=EnvironmentDomain.SNOW_ICE,
        subsystem="STATION_SNOW",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.IMPLIED,
        physical_quantity=PhysicalQuantity.RATE,
        unit="mm_h",
        sampling_interval_seconds=60.0,
        location_scope="LOCAL_STATION",
        measurement_zone="STATION_PERIMETER",
        min_value=-10.0,
        max_value=50.0,
        default_value=0.2,
        state_path="snow.accumulation_rate_mm_h",
        description="Rate of snow accumulation (+) or sublimation/ablation (-).",
    ),
    "ENV-SNOW-DRIFT": SensorConfig(
        sensor_id="ENV-SNOW-DRIFT",
        name="Blowing Snow Mass Flux",
        asset_id="STATION_SNOW_ARRAY",
        domain=EnvironmentDomain.SNOW_ICE,
        subsystem="STATION_SNOW",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.IMPLIED,
        physical_quantity=PhysicalQuantity.MASS_FLUX,
        unit="g_m2_s",
        sampling_interval_seconds=10.0,
        location_scope="LOCAL_STATION",
        measurement_zone="STATION_PERIMETER",
        min_value=0.0,
        max_value=150.0,
        default_value=1.5,
        state_path="snow.drift_mass_flux_g_m2_s",
        description="Blowing snow horizontal mass transport flux from acoustic sensor.",
    ),

    # Coastal / Access Sea Ice (location_scope="COASTAL", measurement_zone="COASTAL_STUDY_AREA")
    "ENV-ICE-PRES": SensorConfig(
        sensor_id="ENV-ICE-PRES",
        name="Fast Ice Presence Flag",
        asset_id="COASTAL_ICE_SYSTEM",
        domain=EnvironmentDomain.SNOW_ICE,
        subsystem="SEA_ICE",
        kind=SensorKind.STATE,
        evidence_level=EvidenceLevel.DOCUMENTED,
        physical_quantity=PhysicalQuantity.PRESENCE,
        unit="bool",
        sampling_interval_seconds=300.0,
        location_scope="COASTAL",
        measurement_zone="COASTAL_STUDY_AREA",
        default_value=True,
        state_path="sea_ice.ice_present",
        description="Coastal sea ice presence verified by radar and ground-truth survey.",
    ),
    "ENV-ICE-THICK": SensorConfig(
        sensor_id="ENV-ICE-THICK",
        name="Fast Ice Thickness",
        asset_id="COASTAL_ICE_SYSTEM",
        domain=EnvironmentDomain.SNOW_ICE,
        subsystem="SEA_ICE",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.IMPLIED,
        physical_quantity=PhysicalQuantity.THICKNESS,
        unit="m",
        sampling_interval_seconds=300.0,
        location_scope="COASTAL",
        measurement_zone="COASTAL_STUDY_AREA",
        min_value=0.0,
        max_value=5.0,
        default_value=1.65,
        state_path="sea_ice.ice_thickness_m",
        description="Fast ice thickness in coastal study and logistics route area.",
    ),
    "ENV-ICE-CONC": SensorConfig(
        sensor_id="ENV-ICE-CONC",
        name="Coastal Sea Ice Concentration",
        asset_id="COASTAL_ICE_SYSTEM",
        domain=EnvironmentDomain.SNOW_ICE,
        subsystem="SEA_ICE",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.IMPLIED,
        physical_quantity=PhysicalQuantity.PERCENT,
        unit="%",
        sampling_interval_seconds=300.0,
        location_scope="COASTAL",
        measurement_zone="COASTAL_STUDY_AREA",
        min_value=0.0,
        max_value=100.0,
        default_value=85.0,
        state_path="sea_ice.ice_concentration_percent",
        description="Fractional sea ice coverage in coastal logistics zone.",
    ),
    "ENV-ICE-TEMP": SensorConfig(
        sensor_id="ENV-ICE-TEMP",
        name="Sea Ice Surface Temperature",
        asset_id="COASTAL_ICE_SYSTEM",
        domain=EnvironmentDomain.SNOW_ICE,
        subsystem="SEA_ICE",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.IMPLIED,
        physical_quantity=PhysicalQuantity.TEMPERATURE,
        unit="degC",
        sampling_interval_seconds=60.0,
        location_scope="COASTAL",
        measurement_zone="COASTAL_STUDY_AREA",
        min_value=-40.0,
        max_value=2.0,
        default_value=-14.5,
        state_path="sea_ice.ice_surface_temperature_c",
        description="Infrared radiometric surface temperature of sea ice.",
    ),
    "ENV-ICE-DRIFT-S": SensorConfig(
        sensor_id="ENV-ICE-DRIFT-S",
        name="Pack Ice Drift Speed",
        asset_id="COASTAL_ICE_SYSTEM",
        domain=EnvironmentDomain.SNOW_ICE,
        subsystem="SEA_ICE",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.NOT_PUBLICLY_CONFIRMED,
        physical_quantity=PhysicalQuantity.VELOCITY,
        unit="m_s",
        sampling_interval_seconds=300.0,
        location_scope="COASTAL",
        measurement_zone="COASTAL_STUDY_AREA",
        min_value=0.0,
        max_value=5.0,
        default_value=0.25,
        state_path="sea_ice.ice_drift_speed_mps",
        description="Drift speed of mobile offshore pack ice.",
    ),
    "ENV-ICE-EDGE": SensorConfig(
        sensor_id="ENV-ICE-EDGE",
        name="Distance to Open Water / Ice Edge",
        asset_id="COASTAL_ICE_SYSTEM",
        domain=EnvironmentDomain.SNOW_ICE,
        subsystem="SEA_ICE",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.NOT_PUBLICLY_CONFIRMED,
        physical_quantity=PhysicalQuantity.DISTANCE,
        unit="km",
        sampling_interval_seconds=300.0,
        location_scope="COASTAL",
        measurement_zone="COASTAL_STUDY_AREA",
        min_value=0.0,
        max_value=150.0,
        default_value=18.0,
        state_path="sea_ice.distance_to_open_water_km",
        description="Distance from Bharati coast to nearest lead / open water edge.",
    ),

    # =========================================================================
    # DOMAIN 5: OCEAN & COASTAL CONTEXT (10 Sensors)
    # All location_scope="COASTAL_CONTEXT", measurement_zone="PRYDZ_BAY_COASTAL"
    # =========================================================================
    "ENV-OCEAN-TEMP": SensorConfig(
        sensor_id="ENV-OCEAN-TEMP",
        name="Coastal Surface Seawater Temperature",
        asset_id="COASTAL_OCEAN_MOORING",
        domain=EnvironmentDomain.OCEAN,
        subsystem="HYDROGRAPHY",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.NOT_PUBLICLY_CONFIRMED,
        physical_quantity=PhysicalQuantity.TEMPERATURE,
        unit="degC",
        sampling_interval_seconds=60.0,
        location_scope="COASTAL_CONTEXT",
        measurement_zone="PRYDZ_BAY_COASTAL",
        min_value=-3.0,
        max_value=5.0,
        default_value=-1.6,
        state_path="ocean.water_temperature_c",
        description="Surface seawater temperature in Prydz Bay coastal waters.",
    ),
    "ENV-OCEAN-SAL": SensorConfig(
        sensor_id="ENV-OCEAN-SAL",
        name="Coastal Seawater Salinity",
        asset_id="COASTAL_OCEAN_MOORING",
        domain=EnvironmentDomain.OCEAN,
        subsystem="HYDROGRAPHY",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.NOT_PUBLICLY_CONFIRMED,
        physical_quantity=PhysicalQuantity.SALINITY,
        unit="PSU",
        sampling_interval_seconds=60.0,
        location_scope="COASTAL_CONTEXT",
        measurement_zone="PRYDZ_BAY_COASTAL",
        min_value=25.0,
        max_value=40.0,
        default_value=34.2,
        state_path="ocean.salinity_psu",
        description="Practical salinity units of coastal seawater.",
    ),
    "ENV-OCEAN-COND": SensorConfig(
        sensor_id="ENV-OCEAN-COND",
        name="Seawater Electrical Conductivity",
        asset_id="COASTAL_OCEAN_MOORING",
        domain=EnvironmentDomain.OCEAN,
        subsystem="HYDROGRAPHY",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.NOT_PUBLICLY_CONFIRMED,
        physical_quantity=PhysicalQuantity.CONDUCTIVITY,
        unit="mS_cm",
        sampling_interval_seconds=60.0,
        location_scope="COASTAL_CONTEXT",
        measurement_zone="PRYDZ_BAY_COASTAL",
        min_value=20.0,
        max_value=45.0,
        default_value=29.5,
        state_path="ocean.conductivity_ms_cm",
        description="Conductivity of coastal seawater from CTD cell.",
    ),
    "ENV-OCEAN-PRESS": SensorConfig(
        sensor_id="ENV-OCEAN-PRESS",
        name="Subsurface Hydrostatic Pressure",
        asset_id="COASTAL_OCEAN_MOORING",
        domain=EnvironmentDomain.OCEAN,
        subsystem="HYDROGRAPHY",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.NOT_PUBLICLY_CONFIRMED,
        physical_quantity=PhysicalQuantity.PRESSURE,
        unit="dbar",
        sampling_interval_seconds=60.0,
        location_scope="COASTAL_CONTEXT",
        measurement_zone="PRYDZ_BAY_COASTAL",
        min_value=0.0,
        max_value=100.0,
        default_value=15.0,
        state_path="ocean.pressure_dbar",
        description="Hydrostatic pressure at coastal mooring depth.",
    ),
    "ENV-OCEAN-CURRENT-S": SensorConfig(
        sensor_id="ENV-OCEAN-CURRENT-S",
        name="Coastal Current Speed",
        asset_id="COASTAL_OCEAN_MOORING",
        domain=EnvironmentDomain.OCEAN,
        subsystem="DYNAMICS",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.NOT_PUBLICLY_CONFIRMED,
        physical_quantity=PhysicalQuantity.VELOCITY,
        unit="m_s",
        sampling_interval_seconds=60.0,
        location_scope="COASTAL_CONTEXT",
        measurement_zone="PRYDZ_BAY_COASTAL",
        min_value=0.0,
        max_value=3.0,
        default_value=0.22,
        state_path="ocean.current_speed_mps",
        description="Acoustic Doppler current profiler coastal horizontal speed.",
    ),
    "ENV-OCEAN-CURRENT-D": SensorConfig(
        sensor_id="ENV-OCEAN-CURRENT-D",
        name="Coastal Current Direction",
        asset_id="COASTAL_OCEAN_MOORING",
        domain=EnvironmentDomain.OCEAN,
        subsystem="DYNAMICS",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.NOT_PUBLICLY_CONFIRMED,
        physical_quantity=PhysicalQuantity.DIRECTION,
        unit="deg",
        sampling_interval_seconds=60.0,
        location_scope="COASTAL_CONTEXT",
        measurement_zone="PRYDZ_BAY_COASTAL",
        min_value=0.0,
        max_value=360.0,
        default_value=240.0,
        state_path="ocean.current_direction_deg",
        description="Compass heading of coastal marine current flow.",
    ),
    "ENV-OCEAN-WAVE-H": SensorConfig(
        sensor_id="ENV-OCEAN-WAVE-H",
        name="Significant Wave Height",
        asset_id="COASTAL_OCEAN_MOORING",
        domain=EnvironmentDomain.OCEAN,
        subsystem="DYNAMICS",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.NOT_PUBLICLY_CONFIRMED,
        physical_quantity=PhysicalQuantity.DEPTH,
        unit="m",
        sampling_interval_seconds=60.0,
        location_scope="COASTAL_CONTEXT",
        measurement_zone="PRYDZ_BAY_COASTAL",
        min_value=0.0,
        max_value=12.0,
        default_value=0.6,
        state_path="ocean.significant_wave_height_m",
        description="Significant wave height Hs in open leads / coastal swell.",
    ),
    "ENV-OCEAN-WAVE-P": SensorConfig(
        sensor_id="ENV-OCEAN-WAVE-P",
        name="Peak Wave Period",
        asset_id="COASTAL_OCEAN_MOORING",
        domain=EnvironmentDomain.OCEAN,
        subsystem="DYNAMICS",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.NOT_PUBLICLY_CONFIRMED,
        physical_quantity=PhysicalQuantity.TIME,
        unit="s",
        sampling_interval_seconds=60.0,
        location_scope="COASTAL_CONTEXT",
        measurement_zone="PRYDZ_BAY_COASTAL",
        min_value=1.0,
        max_value=30.0,
        default_value=6.5,
        state_path="ocean.wave_period_s",
        description="Dominant wave energy spectral peak period.",
    ),
    "ENV-OCEAN-LEVEL": SensorConfig(
        sensor_id="ENV-OCEAN-LEVEL",
        name="Tidal Sea Level Anomaly",
        asset_id="COASTAL_OCEAN_MOORING",
        domain=EnvironmentDomain.OCEAN,
        subsystem="DYNAMICS",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.NOT_PUBLICLY_CONFIRMED,
        physical_quantity=PhysicalQuantity.DEPTH,
        unit="m",
        sampling_interval_seconds=60.0,
        location_scope="COASTAL_CONTEXT",
        measurement_zone="PRYDZ_BAY_COASTAL",
        min_value=-3.0,
        max_value=3.0,
        default_value=0.15,
        state_path="ocean.sea_level_anomaly_m",
        description="Coastal tidal height variation above chart datum.",
    ),
    "ENV-OCEAN-TURB": SensorConfig(
        sensor_id="ENV-OCEAN-TURB",
        name="Coastal Seawater Turbidity",
        asset_id="COASTAL_OCEAN_MOORING",
        domain=EnvironmentDomain.OCEAN,
        subsystem="HYDROGRAPHY",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.NOT_PUBLICLY_CONFIRMED,
        physical_quantity=PhysicalQuantity.TURBIDITY,
        unit="NTU",
        sampling_interval_seconds=60.0,
        location_scope="COASTAL_CONTEXT",
        measurement_zone="PRYDZ_BAY_COASTAL",
        min_value=0.0,
        max_value=50.0,
        default_value=1.2,
        state_path="ocean.turbidity_ntu",
        description="Optical backscatter nephelometric turbidity in coastal water.",
    ),

    # =========================================================================
    # DOMAIN 6: ENVIRONMENTAL WATER / LIMNOLOGY (7 Sensors)
    # Natural proglacial/meltwater monitoring (distinct from station potable/RO)
    # =========================================================================
    "ENV-WATER-TEMP": SensorConfig(
        sensor_id="ENV-WATER-TEMP",
        name="Natural Meltwater Lake Temperature",
        asset_id="MELTWATER_LAKE_MONITOR",
        domain=EnvironmentDomain.ENVIRONMENTAL_WATER,
        subsystem="LIMNOLOGY",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.DOCUMENTED,
        physical_quantity=PhysicalQuantity.TEMPERATURE,
        unit="degC",
        sampling_interval_seconds=60.0,
        min_value=-2.0,
        max_value=15.0,
        default_value=3.2,
        state_path="environmental_water.water_temperature_c",
        description="Temperature of natural proglacial meltwater lake (e.g. Lake Progress).",
    ),
    "ENV-WATER-PH": SensorConfig(
        sensor_id="ENV-WATER-PH",
        name="Natural Meltwater pH",
        asset_id="MELTWATER_LAKE_MONITOR",
        domain=EnvironmentDomain.ENVIRONMENTAL_WATER,
        subsystem="LIMNOLOGY",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.DOCUMENTED,
        physical_quantity=PhysicalQuantity.PH,
        unit="pH",
        sampling_interval_seconds=60.0,
        min_value=4.0,
        max_value=10.0,
        default_value=7.4,
        state_path="environmental_water.ph",
        description="Acidity / alkalinity pH of natural meltwater lake.",
    ),
    "ENV-WATER-COND": SensorConfig(
        sensor_id="ENV-WATER-COND",
        name="Natural Water Specific Conductivity",
        asset_id="MELTWATER_LAKE_MONITOR",
        domain=EnvironmentDomain.ENVIRONMENTAL_WATER,
        subsystem="LIMNOLOGY",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.DOCUMENTED,
        physical_quantity=PhysicalQuantity.CONDUCTIVITY,
        unit="uS_cm",
        sampling_interval_seconds=60.0,
        min_value=1.0,
        max_value=1500.0,
        default_value=45.0,
        state_path="environmental_water.conductivity_us_cm",
        description="Electrical conductivity in natural freshwater lake.",
    ),
    "ENV-WATER-TURB": SensorConfig(
        sensor_id="ENV-WATER-TURB",
        name="Natural Water Turbidity",
        asset_id="MELTWATER_LAKE_MONITOR",
        domain=EnvironmentDomain.ENVIRONMENTAL_WATER,
        subsystem="LIMNOLOGY",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.IMPLIED,
        physical_quantity=PhysicalQuantity.TURBIDITY,
        unit="NTU",
        sampling_interval_seconds=60.0,
        min_value=0.0,
        max_value=100.0,
        default_value=0.8,
        state_path="environmental_water.turbidity_ntu",
        description="Suspended sediment turbidity in proglacial meltwater stream.",
    ),
    "ENV-WATER-DO": SensorConfig(
        sensor_id="ENV-WATER-DO",
        name="Natural Water Dissolved Oxygen",
        asset_id="MELTWATER_LAKE_MONITOR",
        domain=EnvironmentDomain.ENVIRONMENTAL_WATER,
        subsystem="LIMNOLOGY",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.IMPLIED,
        physical_quantity=PhysicalQuantity.MASS_CONCENTRATION,
        unit="mg_L",
        sampling_interval_seconds=60.0,
        min_value=0.0,
        max_value=20.0,
        default_value=12.5,
        state_path="environmental_water.dissolved_oxygen_mg_l",
        description="Dissolved oxygen concentration in natural lake ecosystem.",
    ),
    "ENV-WATER-CONT": SensorConfig(
        sensor_id="ENV-WATER-CONT",
        name="Natural Water Contamination Index",
        asset_id="MELTWATER_LAKE_MONITOR",
        domain=EnvironmentDomain.ENVIRONMENTAL_WATER,
        subsystem="LIMNOLOGY",
        kind=SensorKind.DERIVED,
        evidence_level=EvidenceLevel.DERIVED,
        physical_quantity=PhysicalQuantity.INDEX,
        unit="score",
        sampling_interval_seconds=60.0,
        min_value=0.0,
        max_value=100.0,
        default_value=2.0,
        state_path="environmental_water.contamination_index",
        state_dependencies=["environmental_water.ph", "environmental_water.conductivity_us_cm", "environmental_water.turbidity_ntu"],
        description="Derived limnological environmental degradation risk index.",
    ),
    "ENV-WATER-HC": SensorConfig(
        sensor_id="ENV-WATER-HC",
        name="Hydrocarbon Trace Fluorescence",
        asset_id="MELTWATER_LAKE_MONITOR",
        domain=EnvironmentDomain.ENVIRONMENTAL_WATER,
        subsystem="LIMNOLOGY",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.NOT_PUBLICLY_CONFIRMED,
        physical_quantity=PhysicalQuantity.MASS_CONCENTRATION,
        unit="ppb",
        sampling_interval_seconds=60.0,
        min_value=0.0,
        max_value=100.0,
        default_value=0.05,
        state_path="environmental_water.hydrocarbon_trace_ppb",
        description="Fluorescence-based hydrocarbon trace detector in coastal runoff.",
    ),

    # =========================================================================
    # DOMAIN 7: ATMOSPHERIC ELECTRICITY (6 Sensors)
    # =========================================================================
    "ENV-ELEC-EFIELD": SensorConfig(
        sensor_id="ENV-ELEC-EFIELD",
        name="Atmospheric Vertical Electric Field",
        asset_id="ATM_ELECTRICITY_LAB",
        domain=EnvironmentDomain.ATMOSPHERIC_ELECTRICITY,
        subsystem="FIELD_MILL",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.DOCUMENTED,
        physical_quantity=PhysicalQuantity.VOLTAGE,
        unit="V_m",
        sampling_interval_seconds=5.0,
        min_value=-500.0,
        max_value=1500.0,
        default_value=85.0,
        state_path="atmospheric_electricity.electric_field_v_m",
        description="Atmospheric potential gradient measured by electric field mill.",
    ),
    "ENV-ELEC-AEC": SensorConfig(
        sensor_id="ENV-ELEC-AEC",
        name="Air-Earth Conduction Current Density",
        asset_id="ATM_ELECTRICITY_LAB",
        domain=EnvironmentDomain.ATMOSPHERIC_ELECTRICITY,
        subsystem="CURRENT_COLLECTOR",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.DOCUMENTED,
        physical_quantity=PhysicalQuantity.CURRENT_DENSITY,
        unit="pA_m2",
        sampling_interval_seconds=10.0,
        min_value=-10.0,
        max_value=25.0,
        default_value=2.1,
        state_path="atmospheric_electricity.air_earth_current_pa_m2",
        description="Air-earth current density collected on horizontal plate.",
    ),
    "ENV-ELEC-MAXWELL": SensorConfig(
        sensor_id="ENV-ELEC-MAXWELL",
        name="Maxwell Current Density",
        asset_id="ATM_ELECTRICITY_LAB",
        domain=EnvironmentDomain.ATMOSPHERIC_ELECTRICITY,
        subsystem="CURRENT_COLLECTOR",
        kind=SensorKind.DERIVED,
        evidence_level=EvidenceLevel.IMPLIED,
        physical_quantity=PhysicalQuantity.CURRENT_DENSITY,
        unit="pA_m2",
        sampling_interval_seconds=10.0,
        min_value=-15.0,
        max_value=35.0,
        default_value=2.3,
        state_path="atmospheric_electricity.maxwell_current_pa_m2",
        state_dependencies=["atmospheric_electricity.air_earth_current_pa_m2", "atmospheric_electricity.electric_field_v_m"],
        description="Total Maxwell current density (conduction + displacement current).",
    ),
    "ENV-ELEC-POS": SensorConfig(
        sensor_id="ENV-ELEC-POS",
        name="Positive Atmospheric Ion Conductivity",
        asset_id="ATM_ELECTRICITY_LAB",
        domain=EnvironmentDomain.ATMOSPHERIC_ELECTRICITY,
        subsystem="GERDIEN_CONDENSER",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.IMPLIED,
        physical_quantity=PhysicalQuantity.CONDUCTIVITY,
        unit="fS_m",
        sampling_interval_seconds=30.0,
        min_value=0.0,
        max_value=50.0,
        default_value=11.5,
        state_path="atmospheric_electricity.positive_conductivity_fs_m",
        description="Atmospheric polar conductivity of positive ions from Gerdien tube.",
    ),
    "ENV-ELEC-NEG": SensorConfig(
        sensor_id="ENV-ELEC-NEG",
        name="Negative Atmospheric Ion Conductivity",
        asset_id="ATM_ELECTRICITY_LAB",
        domain=EnvironmentDomain.ATMOSPHERIC_ELECTRICITY,
        subsystem="GERDIEN_CONDENSER",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.IMPLIED,
        physical_quantity=PhysicalQuantity.CONDUCTIVITY,
        unit="fS_m",
        sampling_interval_seconds=30.0,
        min_value=0.0,
        max_value=50.0,
        default_value=9.8,
        state_path="atmospheric_electricity.negative_conductivity_fs_m",
        description="Atmospheric polar conductivity of negative ions from Gerdien tube.",
    ),
    "ENV-ELEC-STATUS": SensorConfig(
        sensor_id="ENV-ELEC-STATUS",
        name="Atmospheric Electricity System Status",
        asset_id="ATM_ELECTRICITY_LAB",
        domain=EnvironmentDomain.ATMOSPHERIC_ELECTRICITY,
        subsystem="LAB_MONITOR",
        kind=SensorKind.STATE,
        evidence_level=EvidenceLevel.DOCUMENTED,
        physical_quantity=PhysicalQuantity.STATUS,
        unit="status",
        sampling_interval_seconds=30.0,
        default_value="OPERATIONAL",
        state_path="atmospheric_electricity.system_status",
        description="Operational health status of atmospheric electricity laboratory.",
    ),

    # =========================================================================
    # DOMAIN 8: SCIENTIFIC ENVIRONMENTAL CONTEXT (10 Sensors)
    # =========================================================================
    "ENV-IONO-TEC": SensorConfig(
        sensor_id="ENV-IONO-TEC",
        name="Ionospheric Total Electron Content",
        asset_id="GNSS_IONO_RECEIVER",
        domain=EnvironmentDomain.SCIENTIFIC_CONTEXT,
        subsystem="IONOSPHERE",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.DOCUMENTED,
        physical_quantity=PhysicalQuantity.ELECTRON_CONTENT,
        unit="TECU",
        sampling_interval_seconds=30.0,
        min_value=0.0,
        max_value=150.0,
        default_value=12.4,
        state_path="ionosphere.total_electron_content_tecu",
        description="Vertical Total Electron Content from dual-frequency NovAtel GNSS.",
    ),
    "ENV-IONO-L1-AMP": SensorConfig(
        sensor_id="ENV-IONO-L1-AMP",
        name="L1 Amplitude Scintillation Index S4",
        asset_id="GNSS_IONO_RECEIVER",
        domain=EnvironmentDomain.SCIENTIFIC_CONTEXT,
        subsystem="IONOSPHERE",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.DOCUMENTED,
        physical_quantity=PhysicalQuantity.INDEX,
        unit="ratio",
        sampling_interval_seconds=30.0,
        min_value=0.0,
        max_value=1.5,
        default_value=0.08,
        state_path="ionosphere.scintillation_s4",
        description="GNSS L1 frequency amplitude scintillation index S4.",
    ),
    "ENV-IONO-L1-PHASE": SensorConfig(
        sensor_id="ENV-IONO-L1-PHASE",
        name="L1 Phase Scintillation Sigma Phi",
        asset_id="GNSS_IONO_RECEIVER",
        domain=EnvironmentDomain.SCIENTIFIC_CONTEXT,
        subsystem="IONOSPHERE",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.DOCUMENTED,
        physical_quantity=PhysicalQuantity.INDEX,
        unit="rad",
        sampling_interval_seconds=30.0,
        min_value=0.0,
        max_value=3.14,
        default_value=0.12,
        state_path="ionosphere.phase_scintillation_rad",
        description="GNSS carrier phase scintillation standard deviation.",
    ),
    "ENV-IONO-STATUS": SensorConfig(
        sensor_id="ENV-IONO-STATUS",
        name="Ionospheric Telemetry Lock Status",
        asset_id="GNSS_IONO_RECEIVER",
        domain=EnvironmentDomain.SCIENTIFIC_CONTEXT,
        subsystem="IONOSPHERE",
        kind=SensorKind.STATE,
        evidence_level=EvidenceLevel.DOCUMENTED,
        physical_quantity=PhysicalQuantity.STATUS,
        unit="status",
        sampling_interval_seconds=30.0,
        default_value="LOCKED",
        state_path="ionosphere.receiver_status",
        description="Tracking lock status of GNSS ionospheric scintillation monitor.",
    ),
    "ENV-SKY-CLOUD": SensorConfig(
        sensor_id="ENV-SKY-CLOUD",
        name="Cloud Cover Fraction",
        asset_id="ALL_SKY_IMAGER",
        domain=EnvironmentDomain.SCIENTIFIC_CONTEXT,
        subsystem="OPTICAL_SKY",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.DOCUMENTED,
        physical_quantity=PhysicalQuantity.PERCENT,
        unit="%",
        sampling_interval_seconds=60.0,
        min_value=0.0,
        max_value=100.0,
        default_value=35.0,
        state_path="sky.cloud_cover_percent",
        description="Total cloud cover percentage observed by all-sky camera/ceilometer.",
    ),
    "ENV-SKY-AURORA": SensorConfig(
        sensor_id="ENV-SKY-AURORA",
        name="Auroral Optical Intensity",
        asset_id="ALL_SKY_IMAGER",
        domain=EnvironmentDomain.SCIENTIFIC_CONTEXT,
        subsystem="OPTICAL_SKY",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.DOCUMENTED,
        physical_quantity=PhysicalQuantity.OPTICAL_INTENSITY,
        unit="kR",
        sampling_interval_seconds=30.0,
        min_value=0.0,
        max_value=500.0,
        default_value=2.5,
        state_path="sky.auroral_intensity_kr",
        description="Green line 557.7nm optical auroral emission in kiloRayleighs.",
    ),
    "ENV-SKY-IMAGE-STAT": SensorConfig(
        sensor_id="ENV-SKY-IMAGE-STAT",
        name="All-Sky Camera Operational Status",
        asset_id="ALL_SKY_IMAGER",
        domain=EnvironmentDomain.SCIENTIFIC_CONTEXT,
        subsystem="OPTICAL_SKY",
        kind=SensorKind.STATE,
        evidence_level=EvidenceLevel.DOCUMENTED,
        physical_quantity=PhysicalQuantity.STATUS,
        unit="status",
        sampling_interval_seconds=60.0,
        default_value="ACTIVE",
        state_path="sky.camera_status",
        description="Operational state of all-sky imager dome heating and shutter.",
    ),
    "ENV-SEIS-ACC": SensorConfig(
        sensor_id="ENV-SEIS-ACC",
        name="Seismic Ground Acceleration",
        asset_id="SEISMIC_OBSERVATORY",
        domain=EnvironmentDomain.SCIENTIFIC_CONTEXT,
        subsystem="SEISMIC",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.DOCUMENTED,
        physical_quantity=PhysicalQuantity.ACCELERATION,
        unit="um_s2",
        sampling_interval_seconds=1.0,
        min_value=0.0,
        max_value=50000.0,
        default_value=0.8,
        state_path="seismic.ground_acceleration_um_s2",
        description="Broadband vertical ground acceleration from seismometer.",
    ),
    "ENV-SEIS-VEL": SensorConfig(
        sensor_id="ENV-SEIS-VEL",
        name="Ground Particle Velocity",
        asset_id="SEISMIC_OBSERVATORY",
        domain=EnvironmentDomain.SCIENTIFIC_CONTEXT,
        subsystem="SEISMIC",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.DOCUMENTED,
        physical_quantity=PhysicalQuantity.VELOCITY,
        unit="um_s",
        sampling_interval_seconds=1.0,
        min_value=0.0,
        max_value=5000.0,
        default_value=0.05,
        state_path="seismic.particle_velocity_um_s",
        description="Particle velocity amplitude at seismological pier.",
    ),
    "ENV-SEIS-EVENT": SensorConfig(
        sensor_id="ENV-SEIS-EVENT",
        name="Seismic Event Detected Flag",
        asset_id="SEISMIC_OBSERVATORY",
        domain=EnvironmentDomain.SCIENTIFIC_CONTEXT,
        subsystem="SEISMIC",
        kind=SensorKind.STATE,
        evidence_level=EvidenceLevel.DOCUMENTED,
        physical_quantity=PhysicalQuantity.PRESENCE,
        unit="bool",
        sampling_interval_seconds=1.0,
        default_value=False,
        state_path="seismic.event_detected",
        description="STA/LTA trigger flag indicating local or teleseismic earthquake.",
    ),

    # =========================================================================
    # DOMAIN 9: DERIVED ENVIRONMENTAL INDICATORS (12 Sensors)
    # All kind=DERIVED, evidence=DERIVED
    # =========================================================================
    "ENV-DERIVED-DEWPOINT": SensorConfig(
        sensor_id="ENV-DERIVED-DEWPOINT",
        name="Derived Atmospheric Dew Point",
        asset_id="DERIVED_INDICATORS_ENGINE",
        domain=EnvironmentDomain.DERIVED_INDICATORS,
        subsystem="DERIVED_ATMOSPHERE",
        kind=SensorKind.DERIVED,
        evidence_level=EvidenceLevel.DERIVED,
        physical_quantity=PhysicalQuantity.TEMPERATURE,
        unit="degC",
        sampling_interval_seconds=10.0,
        min_value=-60.0,
        max_value=15.0,
        default_value=-22.5,
        state_path="derived.dew_point_c",
        state_dependencies=["weather.ambient_temperature_c", "weather.relative_humidity_percent"],
        description="Deterministic Magnus dew point indicator.",
    ),
    "ENV-DERIVED-AIR-DENSITY": SensorConfig(
        sensor_id="ENV-DERIVED-AIR-DENSITY",
        name="Derived Moist Air Density",
        asset_id="DERIVED_INDICATORS_ENGINE",
        domain=EnvironmentDomain.DERIVED_INDICATORS,
        subsystem="DERIVED_ATMOSPHERE",
        kind=SensorKind.DERIVED,
        evidence_level=EvidenceLevel.DERIVED,
        physical_quantity=PhysicalQuantity.MASS_CONCENTRATION,
        unit="kg_m3",
        sampling_interval_seconds=10.0,
        min_value=0.9,
        max_value=1.6,
        default_value=1.34,
        state_path="derived.air_density_kg_m3",
        state_dependencies=["weather.atmospheric_pressure_hpa", "weather.ambient_temperature_c", "weather.relative_humidity_percent"],
        description="Deterministic CIPM moist air density indicator.",
    ),
    "ENV-DERIVED-WIND-CHILL": SensorConfig(
        sensor_id="ENV-DERIVED-WIND-CHILL",
        name="Antarctic Wind Chill Index",
        asset_id="DERIVED_INDICATORS_ENGINE",
        domain=EnvironmentDomain.DERIVED_INDICATORS,
        subsystem="DERIVED_ATMOSPHERE",
        kind=SensorKind.DERIVED,
        evidence_level=EvidenceLevel.DERIVED,
        physical_quantity=PhysicalQuantity.TEMPERATURE,
        unit="degC",
        sampling_interval_seconds=10.0,
        min_value=-75.0,
        max_value=15.0,
        default_value=-29.8,
        state_path="derived.wind_chill_c",
        state_dependencies=["weather.ambient_temperature_c", "weather.wind_speed_mps"],
        description="JAG/TI standard wind chill equivalent temperature index.",
    ),
    "ENV-DERIVED-COLD-STRESS": SensorConfig(
        sensor_id="ENV-DERIVED-COLD-STRESS",
        name="Outdoor Personnel Cold Stress Risk",
        asset_id="DERIVED_INDICATORS_ENGINE",
        domain=EnvironmentDomain.DERIVED_INDICATORS,
        subsystem="DERIVED_RISK",
        kind=SensorKind.DERIVED,
        evidence_level=EvidenceLevel.DERIVED,
        physical_quantity=PhysicalQuantity.INDEX,
        unit="score",
        sampling_interval_seconds=10.0,
        min_value=0.0,
        max_value=100.0,
        default_value=35.0,
        state_path="derived.cold_stress_risk",
        state_dependencies=["weather.ambient_temperature_c", "weather.wind_speed_mps", "radiation.shortwave_downwelling_w_m2"],
        description="Outdoor personnel frostbite/hypothermia risk score (0-100).",
    ),
    "ENV-DERIVED-BLIZZARD-RISK": SensorConfig(
        sensor_id="ENV-DERIVED-BLIZZARD-RISK",
        name="Antarctic Blizzard Risk Score",
        asset_id="DERIVED_INDICATORS_ENGINE",
        domain=EnvironmentDomain.DERIVED_INDICATORS,
        subsystem="DERIVED_RISK",
        kind=SensorKind.DERIVED,
        evidence_level=EvidenceLevel.DERIVED,
        physical_quantity=PhysicalQuantity.INDEX,
        unit="score",
        sampling_interval_seconds=10.0,
        min_value=0.0,
        max_value=100.0,
        default_value=12.0,
        state_path="derived.blizzard_risk",
        state_dependencies=["weather.wind_speed_mps", "weather.wind_gust_mps", "weather.visibility_m", "snow.drift_mass_flux_g_m2_s", "weather.pressure_tendency_hpa_3h"],
        description="Coupled Antarctic blizzard risk index evaluating wind, gust, blowing snow, and pressure tendency.",
    ),
    "ENV-DERIVED-FREEZE-RISK": SensorConfig(
        sensor_id="ENV-DERIVED-FREEZE-RISK",
        name="External Infrastructure Freeze Risk",
        asset_id="DERIVED_INDICATORS_ENGINE",
        domain=EnvironmentDomain.DERIVED_INDICATORS,
        subsystem="DERIVED_RISK",
        kind=SensorKind.DERIVED,
        evidence_level=EvidenceLevel.DERIVED,
        physical_quantity=PhysicalQuantity.INDEX,
        unit="score",
        sampling_interval_seconds=10.0,
        min_value=0.0,
        max_value=100.0,
        default_value=40.0,
        state_path="derived.freeze_risk",
        state_dependencies=["weather.ambient_temperature_c", "weather.wind_speed_mps"],
        description="External pipe/intake rapid freezing threat score (0-100).",
    ),
    "ENV-DERIVED-SNOW-ACCESS-RISK": SensorConfig(
        sensor_id="ENV-DERIVED-SNOW-ACCESS-RISK",
        name="Snow Access & Obstruction Risk",
        asset_id="DERIVED_INDICATORS_ENGINE",
        domain=EnvironmentDomain.DERIVED_INDICATORS,
        subsystem="DERIVED_RISK",
        kind=SensorKind.DERIVED,
        evidence_level=EvidenceLevel.DERIVED,
        physical_quantity=PhysicalQuantity.INDEX,
        unit="score",
        sampling_interval_seconds=60.0,
        min_value=0.0,
        max_value=100.0,
        default_value=15.0,
        state_path="derived.snow_access_risk",
        state_dependencies=["snow.snow_depth_m", "snow.drift_mass_flux_g_m2_s"],
        description="Ground vehicle & emergency exit snow obstruction risk.",
    ),
    "ENV-DERIVED-ICE-ACCESS-RISK": SensorConfig(
        sensor_id="ENV-DERIVED-ICE-ACCESS-RISK",
        name="Sea Ice Trafficability Risk",
        asset_id="DERIVED_INDICATORS_ENGINE",
        domain=EnvironmentDomain.DERIVED_INDICATORS,
        subsystem="DERIVED_RISK",
        kind=SensorKind.DERIVED,
        evidence_level=EvidenceLevel.DERIVED,
        physical_quantity=PhysicalQuantity.INDEX,
        unit="score",
        sampling_interval_seconds=300.0,
        min_value=0.0,
        max_value=100.0,
        default_value=20.0,
        state_path="derived.ice_access_risk",
        state_dependencies=["sea_ice.ice_thickness_m", "sea_ice.ice_concentration_percent", "sea_ice.ice_surface_temperature_c"],
        description="Fast-ice heavy vehicle transit and logistic route risk (0-100).",
    ),
    "ENV-DERIVED-SOLAR-AVAILABILITY": SensorConfig(
        sensor_id="ENV-DERIVED-SOLAR-AVAILABILITY",
        name="Derived Solar Availability Factor",
        asset_id="DERIVED_INDICATORS_ENGINE",
        domain=EnvironmentDomain.DERIVED_INDICATORS,
        subsystem="DERIVED_ENERGY",
        kind=SensorKind.DERIVED,
        evidence_level=EvidenceLevel.DERIVED,
        physical_quantity=PhysicalQuantity.PERCENT,
        unit="%",
        sampling_interval_seconds=10.0,
        min_value=0.0,
        max_value=100.0,
        default_value=25.0,
        state_path="derived.solar_availability_percent",
        state_dependencies=["radiation.shortwave_downwelling_w_m2", "radiation.is_daylight"],
        description="Normalized solar power environmental generation potential.",
    ),
    "ENV-DERIVED-VISIBILITY-RISK": SensorConfig(
        sensor_id="ENV-DERIVED-VISIBILITY-RISK",
        name="Atmospheric Visibility Impairment Risk",
        asset_id="DERIVED_INDICATORS_ENGINE",
        domain=EnvironmentDomain.DERIVED_INDICATORS,
        subsystem="DERIVED_RISK",
        kind=SensorKind.DERIVED,
        evidence_level=EvidenceLevel.DERIVED,
        physical_quantity=PhysicalQuantity.INDEX,
        unit="score",
        sampling_interval_seconds=10.0,
        min_value=0.0,
        max_value=100.0,
        default_value=8.0,
        state_path="derived.visibility_risk",
        state_dependencies=["weather.visibility_m", "snow.drift_mass_flux_g_m2_s"],
        description="Visual disorientation and whiteout risk index (0-100).",
    ),
    "ENV-DERIVED-ENVIRONMENTAL-RISK": SensorConfig(
        sensor_id="ENV-DERIVED-ENVIRONMENTAL-RISK",
        name="Composite Station Environmental Threat Score",
        asset_id="DERIVED_INDICATORS_ENGINE",
        domain=EnvironmentDomain.DERIVED_INDICATORS,
        subsystem="DERIVED_RISK",
        kind=SensorKind.DERIVED,
        evidence_level=EvidenceLevel.DERIVED,
        physical_quantity=PhysicalQuantity.INDEX,
        unit="score",
        sampling_interval_seconds=10.0,
        min_value=0.0,
        max_value=100.0,
        default_value=24.0,
        state_path="derived.environmental_risk",
        state_dependencies=["derived.blizzard_risk", "derived.cold_stress_risk", "derived.freeze_risk", "derived.visibility_risk"],
        description="Weighted composite risk score aggregating blizzard, cold, and visibility.",
    ),
    "ENV-DERIVED-OPERATING-CONDITION": SensorConfig(
        sensor_id="ENV-DERIVED-OPERATING-CONDITION",
        name="Environmental Operating Condition State",
        asset_id="DERIVED_INDICATORS_ENGINE",
        domain=EnvironmentDomain.DERIVED_INDICATORS,
        subsystem="DERIVED_OPERATIONS",
        kind=SensorKind.DERIVED,
        evidence_level=EvidenceLevel.DERIVED,
        physical_quantity=PhysicalQuantity.STATUS,
        unit="status",
        sampling_interval_seconds=10.0,
        default_value="GREEN (NOMINAL_CONDITIONS)",
        state_path="derived.operating_condition_summary",
        state_dependencies=["weather.wind_speed_mps", "weather.visibility_m", "weather.ambient_temperature_c", "derived.blizzard_risk"],
        description="Antarctic station operating severity level with explainable contributing reasons.",
    ),
}
