"""Configuration parameters, sensor catalogs, and simulation assumptions for Bharati Energy.

Part of SIH 2026 Project SIH26060: F.R.I.D.A.Y.
"""

from __future__ import annotations

from .models import SensorCategory, SensorConfig, SensorKind

# ==============================================================================
# Station Metadata & Defaults
# ==============================================================================
STATION_NAME = "BHARATI"
DOMAIN_NAME = "ENERGY"
SOURCE_REFERENCE_DEFAULT = "bharati_energy_physics_v1"

# ==============================================================================
# Documented NCPOR Grounding & Simulation Assumptions
# ==============================================================================
# Three 100 kVA diesel-operated CHP units documented by NCPOR
CHP_COUNT = 3
CHP_RATING_KVA = 100.0  # Documented rating per CHP
CHP_NOMINAL_VOLTAGE_V = 400.0  # 3-phase line-to-line 400V
CHP_NOMINAL_FREQUENCY_HZ = 50.0  # 50 Hz nominal grid
CHP_NOMINAL_RPM = 1500.0  # 1500 RPM for 4-pole 50 Hz alternator

# Two 60 kVA UPS plants documented by NCPOR
UPS_COUNT = 2
UPS_RATING_KVA = 60.0  # Documented rating per UPS
UPS_NOMINAL_VOLTAGE_V = 400.0  # 3-phase output
UPS_BATTERY_NOMINAL_V = 384.0  # Simulation assumption / configurable nominal DC bus
UPS_DEFAULT_MODULE_COUNT = 30  # Simulation assumption / configurable module count

# Fuel Infrastructure
# NCPOR describes ~3 lakh litre fuel farm across 13 double-hulled tanks (~24,000 L each)
FUEL_FARM_CAPACITY_L = 312_000.0  # Modeled nominal capacity (13 x 24,000 L) (SIMULATION ASSUMPTION)
DAY_TANK_CAPACITY_L = 1_000.0  # Configurable day tank capacity (SIMULATION ASSUMPTION)
DAY_TANK_REFILL_THRESHOLD_L = 400.0  # Setpoint triggering transfer from bulk farm (SIMULATION ASSUMPTION)
DAY_TANK_REFILL_TARGET_L = 900.0  # Setpoint stopping transfer from bulk farm (SIMULATION ASSUMPTION)
FUEL_TRANSFER_PUMP_FLOW_LPH = 1200.0  # Bulk to day tank transfer flow rate (SIMULATION ASSUMPTION)

# Fuel consumption & energetics
# ~0.25 L/kWh baseline specific consumption (SIMULATION ASSUMPTION — not a documented NCPOR constant)
FUEL_CONSUMPTION_FACTOR_L_PER_KWH = 0.25
FUEL_IDLE_CONSUMPTION_LPH = 3.5  # Zero-load idle consumption
# Antarctic diesel lower heating value (SIMULATION ASSUMPTION / configurable fuel property)
DIESEL_LHV_KWH_PER_L = 9.89

# Heating / Thermal System
# NCPOR documented constraint: Maximum station thermal energy demand is approx 155 kWth
MAX_STATION_HEATING_DEMAND_KW = 155.0  # Documented demand bound
CHP_THERMAL_RECOVERY_RATIO = 1.15  # Gross recoverable heat ratio per kW electrical (SIMULATION ASSUMPTION)
GLYCOL_LOOP_PRESSURE_NOMINAL_BAR = 2.0  # Nominal heating loop pressure (SIMULATION ASSUMPTION)

# Sampling intervals (Simulation choices for telemetry modeling)
SAMPLING_INTERVAL_ELECTRICAL = 1.0  # seconds
SAMPLING_INTERVAL_MECHANICAL = 2.0
SAMPLING_INTERVAL_THERMAL = 5.0
SAMPLING_INTERVAL_PRESSURE = 2.0
SAMPLING_INTERVAL_FUEL = 30.0
SAMPLING_INTERVAL_STATUS = 1.0
SAMPLING_INTERVAL_DERIVED = 1.0


def build_chp_sensor_configs(chp_index: int) -> list[SensorConfig]:
    """Generate sensor configurations for a specific CHP unit (1-indexed)."""
    idx_str = f"{chp_index:02d}"
    asset = f"CHP-{chp_index}"
    prefix = f"BHARATI.CHP.{idx_str}"

    return [
        SensorConfig(
            sensor_id=f"{prefix}.POWER",
            asset=asset,
            category=SensorCategory.CHP,
            kind=SensorKind.INSTRUMENT,
            parameter="active_power_kw",
            unit="kW",
            sampling_interval_seconds=SAMPLING_INTERVAL_ELECTRICAL,
            min_valid=0.0,
            max_valid=105.0,
            default_value=0.0,
            sensor_type="POWER_METER",
            description=f"{asset} active power output",
        ),
        SensorConfig(
            sensor_id=f"{prefix}.APPARENT_POWER",
            asset=asset,
            category=SensorCategory.CHP,
            kind=SensorKind.INSTRUMENT,
            parameter="apparent_power_kva",
            unit="kVA",
            sampling_interval_seconds=SAMPLING_INTERVAL_ELECTRICAL,
            min_valid=0.0,
            max_valid=115.0,
            default_value=0.0,
            sensor_type="POWER_METER",
            description=f"{asset} apparent power output",
        ),
        SensorConfig(
            sensor_id=f"{prefix}.VOLTAGE",
            asset=asset,
            category=SensorCategory.CHP,
            kind=SensorKind.INSTRUMENT,
            parameter="voltage",
            unit="V",
            sampling_interval_seconds=SAMPLING_INTERVAL_ELECTRICAL,
            min_valid=350.0,
            max_valid=450.0,
            default_value=400.0,
            sensor_type="VOLTMETER",
            description=f"{asset} line-to-line AC voltage",
        ),
        SensorConfig(
            sensor_id=f"{prefix}.CURRENT",
            asset=asset,
            category=SensorCategory.CHP,
            kind=SensorKind.INSTRUMENT,
            parameter="current",
            unit="A",
            sampling_interval_seconds=SAMPLING_INTERVAL_ELECTRICAL,
            min_valid=0.0,
            max_valid=165.0,
            default_value=0.0,
            sensor_type="AMMETER",
            description=f"{asset} alternator output current",
        ),
        SensorConfig(
            sensor_id=f"{prefix}.FREQUENCY",
            asset=asset,
            category=SensorCategory.CHP,
            kind=SensorKind.INSTRUMENT,
            parameter="frequency_hz",
            unit="Hz",
            sampling_interval_seconds=SAMPLING_INTERVAL_ELECTRICAL,
            min_valid=45.0,
            max_valid=55.0,
            default_value=50.0,
            sensor_type="FREQUENCY_METER",
            description=f"{asset} generator electrical frequency",
        ),
        SensorConfig(
            sensor_id=f"{prefix}.PF",
            asset=asset,
            category=SensorCategory.CHP,
            kind=SensorKind.INSTRUMENT,
            parameter="power_factor",
            unit="dimensionless",
            sampling_interval_seconds=SAMPLING_INTERVAL_ELECTRICAL,
            min_valid=0.5,
            max_valid=1.0,
            default_value=0.88,
            sensor_type="POWER_FACTOR_METER",
            description=f"{asset} alternator power factor",
        ),
        SensorConfig(
            sensor_id=f"{prefix}.RPM",
            asset=asset,
            category=SensorCategory.CHP,
            kind=SensorKind.INSTRUMENT,
            parameter="rpm",
            unit="RPM",
            sampling_interval_seconds=SAMPLING_INTERVAL_MECHANICAL,
            min_valid=0.0,
            max_valid=1800.0,
            default_value=0.0,
            sensor_type="TACHOMETER",
            description=f"{asset} engine rotational speed",
        ),
        SensorConfig(
            sensor_id=f"{prefix}.RUNNING_STATUS",
            asset=asset,
            category=SensorCategory.CHP,
            kind=SensorKind.STATE,
            parameter="running_status",
            unit="bool",
            sampling_interval_seconds=SAMPLING_INTERVAL_STATUS,
            default_value=False,
            sensor_type="STATUS_INDICATOR",
            description=f"{asset} running status flag",
        ),
        SensorConfig(
            sensor_id=f"{prefix}.OPERATING_STATE",
            asset=asset,
            category=SensorCategory.CHP,
            kind=SensorKind.STATE,
            parameter="operating_state",
            unit="state",
            sampling_interval_seconds=SAMPLING_INTERVAL_STATUS,
            default_value="STANDBY",
            sensor_type="STATE_INDICATOR",
            description=f"{asset} operational state (RUNNING, STANDBY, OFF, MAINTENANCE)",
        ),
        SensorConfig(
            sensor_id=f"{prefix}.EXHAUST_TEMP",
            asset=asset,
            category=SensorCategory.CHP,
            kind=SensorKind.INSTRUMENT,
            parameter="exhaust_temperature_c",
            unit="°C",
            sampling_interval_seconds=SAMPLING_INTERVAL_THERMAL,
            min_valid=0.0,
            max_valid=650.0,
            default_value=25.0,
            sensor_type="THERMOCOUPLE",
            description=f"{asset} exhaust gas temperature",
        ),
        SensorConfig(
            sensor_id=f"{prefix}.COOLANT_TEMP",
            asset=asset,
            category=SensorCategory.CHP,
            kind=SensorKind.INSTRUMENT,
            parameter="coolant_temperature_c",
            unit="°C",
            sampling_interval_seconds=SAMPLING_INTERVAL_THERMAL,
            min_valid=0.0,
            max_valid=115.0,
            default_value=25.0,
            sensor_type="RTD",
            description=f"{asset} engine coolant temperature",
        ),
        SensorConfig(
            sensor_id=f"{prefix}.OIL_PRESSURE",
            asset=asset,
            category=SensorCategory.CHP,
            kind=SensorKind.INSTRUMENT,
            parameter="oil_pressure",
            unit="bar",
            sampling_interval_seconds=SAMPLING_INTERVAL_PRESSURE,
            min_valid=0.0,
            max_valid=8.0,
            default_value=0.0,
            sensor_type="PRESSURE_TRANSMITTER",
            description=f"{asset} lube oil pressure",
        ),
        SensorConfig(
            sensor_id=f"{prefix}.COOLANT_PRESSURE",
            asset=asset,
            category=SensorCategory.CHP,
            kind=SensorKind.INSTRUMENT,
            parameter="coolant_pressure",
            unit="bar",
            sampling_interval_seconds=SAMPLING_INTERVAL_PRESSURE,
            min_valid=0.0,
            max_valid=4.0,
            default_value=0.0,
            sensor_type="PRESSURE_TRANSMITTER",
            description=f"{asset} coolant loop pressure",
        ),
        SensorConfig(
            sensor_id=f"{prefix}.FUEL_CONSUMPTION",
            asset=asset,
            category=SensorCategory.CHP,
            kind=SensorKind.INSTRUMENT,
            parameter="fuel_consumption_lph",
            unit="L/h",
            sampling_interval_seconds=SAMPLING_INTERVAL_FUEL,
            min_valid=0.0,
            max_valid=45.0,
            default_value=0.0,
            sensor_type="FLOW_METER",
            description=f"{asset} instantaneous fuel consumption rate",
        ),
        SensorConfig(
            sensor_id=f"{prefix}.RUNTIME_HOURS",
            asset=asset,
            category=SensorCategory.CHP,
            kind=SensorKind.INSTRUMENT,
            parameter="runtime_hours",
            unit="h",
            sampling_interval_seconds=60.0,
            min_valid=0.0,
            max_valid=150000.0,
            default_value=0.0,
            sensor_type="HOUR_METER",
            description=f"{asset} accumulated operating runtime",
        ),
    ]


def build_ups_sensor_configs(ups_index: int) -> list[SensorConfig]:
    """Generate sensor configurations for a specific UPS plant (1-indexed)."""
    idx_str = f"{ups_index:02d}"
    asset = f"UPS-{ups_index}"
    prefix = f"BHARATI.UPS.{idx_str}"

    return [
        # Input measurements
        SensorConfig(
            sensor_id=f"{prefix}.INPUT_VOLTAGE_L1",
            asset=asset,
            category=SensorCategory.UPS,
            kind=SensorKind.INSTRUMENT,
            parameter="input_voltage_l1",
            unit="V",
            sampling_interval_seconds=SAMPLING_INTERVAL_ELECTRICAL,
            min_valid=180.0,
            max_valid=270.0,
            default_value=230.0,
            sensor_type="VOLTMETER",
            description=f"{asset} phase L1 input voltage",
        ),
        SensorConfig(
            sensor_id=f"{prefix}.INPUT_VOLTAGE_L2",
            asset=asset,
            category=SensorCategory.UPS,
            kind=SensorKind.INSTRUMENT,
            parameter="input_voltage_l2",
            unit="V",
            sampling_interval_seconds=SAMPLING_INTERVAL_ELECTRICAL,
            min_valid=180.0,
            max_valid=270.0,
            default_value=230.0,
            sensor_type="VOLTMETER",
            description=f"{asset} phase L2 input voltage",
        ),
        SensorConfig(
            sensor_id=f"{prefix}.INPUT_VOLTAGE_L3",
            asset=asset,
            category=SensorCategory.UPS,
            kind=SensorKind.INSTRUMENT,
            parameter="input_voltage_l3",
            unit="V",
            sampling_interval_seconds=SAMPLING_INTERVAL_ELECTRICAL,
            min_valid=180.0,
            max_valid=270.0,
            default_value=230.0,
            sensor_type="VOLTMETER",
            description=f"{asset} phase L3 input voltage",
        ),
        SensorConfig(
            sensor_id=f"{prefix}.INPUT_FREQ",
            asset=asset,
            category=SensorCategory.UPS,
            kind=SensorKind.INSTRUMENT,
            parameter="input_frequency_hz",
            unit="Hz",
            sampling_interval_seconds=SAMPLING_INTERVAL_ELECTRICAL,
            min_valid=45.0,
            max_valid=55.0,
            default_value=50.0,
            sensor_type="FREQUENCY_METER",
            description=f"{asset} mains input frequency",
        ),
        # Bypass measurements
        SensorConfig(
            sensor_id=f"{prefix}.BYPASS_VOLTAGE",
            asset=asset,
            category=SensorCategory.UPS,
            kind=SensorKind.INSTRUMENT,
            parameter="bypass_voltage",
            unit="V",
            sampling_interval_seconds=SAMPLING_INTERVAL_ELECTRICAL,
            min_valid=350.0,
            max_valid=450.0,
            default_value=400.0,
            sensor_type="VOLTMETER",
            description=f"{asset} bypass line-to-line voltage",
        ),
        SensorConfig(
            sensor_id=f"{prefix}.BYPASS_FREQ",
            asset=asset,
            category=SensorCategory.UPS,
            kind=SensorKind.INSTRUMENT,
            parameter="bypass_frequency_hz",
            unit="Hz",
            sampling_interval_seconds=SAMPLING_INTERVAL_ELECTRICAL,
            min_valid=45.0,
            max_valid=55.0,
            default_value=50.0,
            sensor_type="FREQUENCY_METER",
            description=f"{asset} bypass frequency",
        ),
        # DC link
        SensorConfig(
            sensor_id=f"{prefix}.DC_LINK_VOLTAGE",
            asset=asset,
            category=SensorCategory.UPS,
            kind=SensorKind.INSTRUMENT,
            parameter="dc_link_voltage",
            unit="V",
            sampling_interval_seconds=SAMPLING_INTERVAL_ELECTRICAL,
            min_valid=340.0,
            max_valid=460.0,
            default_value=400.0,
            sensor_type="VOLTMETER",
            description=f"{asset} internal DC link bus voltage",
        ),
        # Output measurements
        SensorConfig(
            sensor_id=f"{prefix}.OUTPUT_VOLTAGE_L1",
            asset=asset,
            category=SensorCategory.UPS,
            kind=SensorKind.INSTRUMENT,
            parameter="output_voltage_l1",
            unit="V",
            sampling_interval_seconds=SAMPLING_INTERVAL_ELECTRICAL,
            min_valid=210.0,
            max_valid=250.0,
            default_value=230.0,
            sensor_type="VOLTMETER",
            description=f"{asset} inverter output phase L1 voltage",
        ),
        SensorConfig(
            sensor_id=f"{prefix}.OUTPUT_VOLTAGE_L2",
            asset=asset,
            category=SensorCategory.UPS,
            kind=SensorKind.INSTRUMENT,
            parameter="output_voltage_l2",
            unit="V",
            sampling_interval_seconds=SAMPLING_INTERVAL_ELECTRICAL,
            min_valid=210.0,
            max_valid=250.0,
            default_value=230.0,
            sensor_type="VOLTMETER",
            description=f"{asset} inverter output phase L2 voltage",
        ),
        SensorConfig(
            sensor_id=f"{prefix}.OUTPUT_VOLTAGE_L3",
            asset=asset,
            category=SensorCategory.UPS,
            kind=SensorKind.INSTRUMENT,
            parameter="output_voltage_l3",
            unit="V",
            sampling_interval_seconds=SAMPLING_INTERVAL_ELECTRICAL,
            min_valid=210.0,
            max_valid=250.0,
            default_value=230.0,
            sensor_type="VOLTMETER",
            description=f"{asset} inverter output phase L3 voltage",
        ),
        SensorConfig(
            sensor_id=f"{prefix}.OUTPUT_FREQ",
            asset=asset,
            category=SensorCategory.UPS,
            kind=SensorKind.INSTRUMENT,
            parameter="output_frequency_hz",
            unit="Hz",
            sampling_interval_seconds=SAMPLING_INTERVAL_ELECTRICAL,
            min_valid=49.0,
            max_valid=51.0,
            default_value=50.0,
            sensor_type="FREQUENCY_METER",
            description=f"{asset} inverter output frequency",
        ),
        SensorConfig(
            sensor_id=f"{prefix}.OUTPUT_CURRENT_L1",
            asset=asset,
            category=SensorCategory.UPS,
            kind=SensorKind.INSTRUMENT,
            parameter="output_current_l1",
            unit="A",
            sampling_interval_seconds=SAMPLING_INTERVAL_ELECTRICAL,
            min_valid=0.0,
            max_valid=100.0,
            default_value=0.0,
            sensor_type="AMMETER",
            description=f"{asset} output current phase L1",
        ),
        SensorConfig(
            sensor_id=f"{prefix}.OUTPUT_CURRENT_L2",
            asset=asset,
            category=SensorCategory.UPS,
            kind=SensorKind.INSTRUMENT,
            parameter="output_current_l2",
            unit="A",
            sampling_interval_seconds=SAMPLING_INTERVAL_ELECTRICAL,
            min_valid=0.0,
            max_valid=100.0,
            default_value=0.0,
            sensor_type="AMMETER",
            description=f"{asset} output current phase L2",
        ),
        SensorConfig(
            sensor_id=f"{prefix}.OUTPUT_CURRENT_L3",
            asset=asset,
            category=SensorCategory.UPS,
            kind=SensorKind.INSTRUMENT,
            parameter="output_current_l3",
            unit="A",
            sampling_interval_seconds=SAMPLING_INTERVAL_ELECTRICAL,
            min_valid=0.0,
            max_valid=100.0,
            default_value=0.0,
            sensor_type="AMMETER",
            description=f"{asset} output current phase L3",
        ),
        # Load measurements
        SensorConfig(
            sensor_id=f"{prefix}.LOAD",
            asset=asset,
            category=SensorCategory.UPS,
            kind=SensorKind.INSTRUMENT,
            parameter="load_percent",
            unit="%",
            sampling_interval_seconds=SAMPLING_INTERVAL_ELECTRICAL,
            min_valid=0.0,
            max_valid=120.0,
            default_value=0.0,
            sensor_type="LOAD_METER",
            description=f"{asset} active load percentage relative to 60 kVA",
        ),
        SensorConfig(
            sensor_id=f"{prefix}.REAL_POWER",
            asset=asset,
            category=SensorCategory.UPS,
            kind=SensorKind.INSTRUMENT,
            parameter="real_power_kw",
            unit="kW",
            sampling_interval_seconds=SAMPLING_INTERVAL_ELECTRICAL,
            min_valid=0.0,
            max_valid=65.0,
            default_value=0.0,
            sensor_type="POWER_METER",
            description=f"{asset} supplied active real power",
        ),
        SensorConfig(
            sensor_id=f"{prefix}.APPARENT_POWER",
            asset=asset,
            category=SensorCategory.UPS,
            kind=SensorKind.INSTRUMENT,
            parameter="apparent_power_kva",
            unit="kVA",
            sampling_interval_seconds=SAMPLING_INTERVAL_ELECTRICAL,
            min_valid=0.0,
            max_valid=70.0,
            default_value=0.0,
            sensor_type="POWER_METER",
            description=f"{asset} supplied apparent power",
        ),
        # Battery system
        SensorConfig(
            sensor_id=f"{prefix}.BATTERY_VOLTAGE",
            asset=asset,
            category=SensorCategory.UPS,
            kind=SensorKind.INSTRUMENT,
            parameter="battery_voltage",
            unit="V",
            sampling_interval_seconds=SAMPLING_INTERVAL_ELECTRICAL,
            min_valid=280.0,
            max_valid=440.0,
            default_value=384.0,
            sensor_type="VOLTMETER",
            description=f"{asset} battery bank terminal voltage",
        ),
        SensorConfig(
            sensor_id=f"{prefix}.BATTERY_CURRENT",
            asset=asset,
            category=SensorCategory.UPS,
            kind=SensorKind.INSTRUMENT,
            parameter="battery_current",
            unit="A",
            sampling_interval_seconds=SAMPLING_INTERVAL_ELECTRICAL,
            min_valid=-150.0,
            max_valid=80.0,
            default_value=0.5,
            sensor_type="AMMETER",
            description=f"{asset} battery current (+ for discharge, - for charge)",
        ),
        SensorConfig(
            sensor_id=f"{prefix}.BATTERY_TEMP",
            asset=asset,
            category=SensorCategory.UPS,
            kind=SensorKind.INSTRUMENT,
            parameter="battery_temperature_c",
            unit="°C",
            sampling_interval_seconds=SAMPLING_INTERVAL_THERMAL,
            min_valid=5.0,
            max_valid=45.0,
            default_value=22.0,
            sensor_type="RTD",
            description=f"{asset} battery enclosure temperature",
        ),
        SensorConfig(
            sensor_id=f"{prefix}.BATTERY_SOC",
            asset=asset,
            category=SensorCategory.UPS,
            kind=SensorKind.INSTRUMENT,
            parameter="battery_capacity_percent",
            unit="%",
            sampling_interval_seconds=SAMPLING_INTERVAL_ELECTRICAL,
            min_valid=0.0,
            max_valid=100.0,
            default_value=100.0,
            sensor_type="SOC_GAUGE",
            description=f"{asset} battery state-of-charge percentage",
        ),
        SensorConfig(
            sensor_id=f"{prefix}.BACKUP_TIME",
            asset=asset,
            category=SensorCategory.UPS,
            kind=SensorKind.INSTRUMENT,
            parameter="backup_time_minutes",
            unit="min",
            sampling_interval_seconds=SAMPLING_INTERVAL_ELECTRICAL,
            min_valid=0.0,
            max_valid=300.0,
            default_value=60.0,
            sensor_type="ESTIMATOR",
            description=f"{asset} estimated battery autonomy at current load",
        ),
        SensorConfig(
            sensor_id=f"{prefix}.CELL_VOLTAGES",
            asset=asset,
            category=SensorCategory.UPS,
            kind=SensorKind.INSTRUMENT,
            parameter="individual_battery_voltages",
            unit="V",
            sampling_interval_seconds=5.0,
            default_value=[],
            sensor_type="BMS_VOLTAGES",
            description=f"{asset} individual battery module voltages",
        ),
        # Status indicators
        SensorConfig(
            sensor_id=f"{prefix}.RECTIFIER_STATUS",
            asset=asset,
            category=SensorCategory.UPS,
            kind=SensorKind.STATE,
            parameter="rectifier_status",
            unit="state",
            sampling_interval_seconds=SAMPLING_INTERVAL_STATUS,
            default_value="NORMAL",
            sensor_type="STATUS_INDICATOR",
            description=f"{asset} rectifier operational status",
        ),
        SensorConfig(
            sensor_id=f"{prefix}.BOOST_STATUS",
            asset=asset,
            category=SensorCategory.UPS,
            kind=SensorKind.STATE,
            parameter="boost_status",
            unit="state",
            sampling_interval_seconds=SAMPLING_INTERVAL_STATUS,
            default_value="INACTIVE",
            sensor_type="STATUS_INDICATOR",
            description=f"{asset} booster/charger boost status",
        ),
        SensorConfig(
            sensor_id=f"{prefix}.BATTERY_STATUS",
            asset=asset,
            category=SensorCategory.UPS,
            kind=SensorKind.STATE,
            parameter="battery_status",
            unit="state",
            sampling_interval_seconds=SAMPLING_INTERVAL_STATUS,
            default_value="FLOAT",
            sensor_type="STATUS_INDICATOR",
            description=f"{asset} battery operational status (FLOAT, DISCHARGE, CHARGE, FAULT)",
        ),
        SensorConfig(
            sensor_id=f"{prefix}.CHARGING_STATUS",
            asset=asset,
            category=SensorCategory.UPS,
            kind=SensorKind.STATE,
            parameter="charging_status",
            unit="state",
            sampling_interval_seconds=SAMPLING_INTERVAL_STATUS,
            default_value="TRICKLE",
            sensor_type="STATUS_INDICATOR",
            description=f"{asset} battery charging mode",
        ),
        SensorConfig(
            sensor_id=f"{prefix}.INVERTER_STATUS",
            asset=asset,
            category=SensorCategory.UPS,
            kind=SensorKind.STATE,
            parameter="inverter_status",
            unit="state",
            sampling_interval_seconds=SAMPLING_INTERVAL_STATUS,
            default_value="NORMAL",
            sensor_type="STATUS_INDICATOR",
            description=f"{asset} inverter status (NORMAL, BYPASS, OFF, FAULT)",
        ),
        SensorConfig(
            sensor_id=f"{prefix}.BYPASS_STATUS",
            asset=asset,
            category=SensorCategory.UPS,
            kind=SensorKind.STATE,
            parameter="bypass_status",
            unit="state",
            sampling_interval_seconds=SAMPLING_INTERVAL_STATUS,
            default_value="AVAILABLE",
            sensor_type="STATUS_INDICATOR",
            description=f"{asset} static bypass switch status",
        ),
        SensorConfig(
            sensor_id=f"{prefix}.LOAD_STATUS",
            asset=asset,
            category=SensorCategory.UPS,
            kind=SensorKind.STATE,
            parameter="load_status",
            unit="state",
            sampling_interval_seconds=SAMPLING_INTERVAL_STATUS,
            default_value="ON_INVERTER",
            sensor_type="STATUS_INDICATOR",
            description=f"{asset} load supply route (ON_INVERTER, ON_BYPASS, ON_BATTERY)",
        ),
        SensorConfig(
            sensor_id=f"{prefix}.FAN_STATUS",
            asset=asset,
            category=SensorCategory.UPS,
            kind=SensorKind.STATE,
            parameter="fan_status",
            unit="state",
            sampling_interval_seconds=SAMPLING_INTERVAL_STATUS,
            default_value="NORMAL",
            sensor_type="STATUS_INDICATOR",
            description=f"{asset} cooling fan subsystem status",
        ),
    ]


def build_fuel_sensor_configs() -> list[SensorConfig]:
    """Generate fuel storage and distribution sensor configurations."""
    asset = "FUEL-SYSTEM"
    return [
        SensorConfig(
            sensor_id="BHARATI.FUEL.BULK.LEVEL",
            asset=asset,
            category=SensorCategory.FUEL,
            kind=SensorKind.INSTRUMENT,
            parameter="bulk_fuel_level_l",
            unit="L",
            sampling_interval_seconds=SAMPLING_INTERVAL_FUEL,
            min_valid=0.0,
            max_valid=FUEL_FARM_CAPACITY_L * 1.05,
            default_value=275_000.0,
            sensor_type="LEVEL_TRANSMITTER",
            description="Fuel Farm aggregate bulk fuel storage level (excluding day tank)",
        ),
        SensorConfig(
            sensor_id="BHARATI.FUEL.BULK.PERCENT",
            asset=asset,
            category=SensorCategory.FUEL,
            kind=SensorKind.INSTRUMENT,
            parameter="bulk_fuel_level_percent",
            unit="%",
            sampling_interval_seconds=SAMPLING_INTERVAL_FUEL,
            min_valid=0.0,
            max_valid=105.0,
            default_value=88.1,
            sensor_type="LEVEL_TRANSMITTER",
            description="Fuel Farm aggregate bulk fuel level percentage",
        ),
        SensorConfig(
            sensor_id="BHARATI.FUEL.DAYTANK.LEVEL",
            asset=asset,
            category=SensorCategory.FUEL,
            kind=SensorKind.INSTRUMENT,
            parameter="day_tank_level_l",
            unit="L",
            sampling_interval_seconds=SAMPLING_INTERVAL_FUEL,
            min_valid=0.0,
            max_valid=DAY_TANK_CAPACITY_L * 1.05,
            default_value=850.0,
            sensor_type="LEVEL_TRANSMITTER",
            description="Power station fuel day tank level",
        ),
        SensorConfig(
            sensor_id="BHARATI.FUEL.DAYTANK.PERCENT",
            asset=asset,
            category=SensorCategory.FUEL,
            kind=SensorKind.INSTRUMENT,
            parameter="day_tank_level_percent",
            unit="%",
            sampling_interval_seconds=SAMPLING_INTERVAL_FUEL,
            min_valid=0.0,
            max_valid=105.0,
            default_value=85.0,
            sensor_type="LEVEL_TRANSMITTER",
            description="Power station fuel day tank percentage",
        ),
        SensorConfig(
            sensor_id="BHARATI.FUEL.TEMPERATURE",
            asset=asset,
            category=SensorCategory.FUEL,
            kind=SensorKind.INSTRUMENT,
            parameter="fuel_temperature_c",
            unit="°C",
            sampling_interval_seconds=SAMPLING_INTERVAL_THERMAL,
            min_valid=-40.0,
            max_valid=40.0,
            default_value=8.0,
            sensor_type="RTD",
            description="Fuel supply line temperature",
        ),
        SensorConfig(
            sensor_id="BHARATI.FUEL.FLOW",
            asset=asset,
            category=SensorCategory.FUEL,
            kind=SensorKind.INSTRUMENT,
            parameter="fuel_flow_lph",
            unit="L/h",
            sampling_interval_seconds=SAMPLING_INTERVAL_FUEL,
            min_valid=0.0,
            max_valid=120.0,
            default_value=0.0,
            sensor_type="FLOW_METER",
            description="Total fuel flow rate from day tank to active CHPs",
        ),
        SensorConfig(
            sensor_id="BHARATI.FUEL.LEAK_STATUS",
            asset=asset,
            category=SensorCategory.FUEL,
            kind=SensorKind.STATE,
            parameter="leak_status",
            unit="state",
            sampling_interval_seconds=SAMPLING_INTERVAL_STATUS,
            default_value="NORMAL",
            sensor_type="LEAK_DETECTOR",
            description="Double-hull / pipeline leak detection status",
        ),
        SensorConfig(
            sensor_id="BHARATI.FUEL.OVERFILL_STATUS",
            asset=asset,
            category=SensorCategory.FUEL,
            kind=SensorKind.STATE,
            parameter="overfill_status",
            unit="state",
            sampling_interval_seconds=SAMPLING_INTERVAL_STATUS,
            default_value="NORMAL",
            sensor_type="LEVEL_SWITCH",
            description="Day tank overfill protection switch status",
        ),
        # Derived fuel sensors
        SensorConfig(
            sensor_id="BHARATI.FUEL.TOTAL_AVAILABLE",
            asset=asset,
            category=SensorCategory.FUEL,
            kind=SensorKind.DERIVED,
            parameter="total_available_fuel_l",
            unit="L",
            sampling_interval_seconds=SAMPLING_INTERVAL_DERIVED,
            min_valid=0.0,
            max_valid=(FUEL_FARM_CAPACITY_L + DAY_TANK_CAPACITY_L) * 1.05,
            default_value=275_850.0,
            sensor_type="CALCULATED_METRIC",
            description="Total station fuel inventory (bulk tanks + day tank)",
        ),
        SensorConfig(
            sensor_id="BHARATI.FUEL.AUTONOMY_HOURS",
            asset=asset,
            category=SensorCategory.FUEL,
            kind=SensorKind.DERIVED,
            parameter="estimated_fuel_autonomy_hours",
            unit="h",
            sampling_interval_seconds=SAMPLING_INTERVAL_DERIVED,
            min_valid=0.0,
            max_valid=50000.0,
            default_value=6000.0,
            sensor_type="CALCULATED_METRIC",
            description="Estimated station fuel autonomy at current consumption rate",
        ),
    ]


def build_heating_sensor_configs() -> list[SensorConfig]:
    """Generate heating and thermal recovery sensor configurations."""
    asset = "HEATING-SYSTEM"
    return [
        SensorConfig(
            sensor_id="BHARATI.HEATING.SUPPLY_TEMP",
            asset=asset,
            category=SensorCategory.HEATING,
            kind=SensorKind.INSTRUMENT,
            parameter="heating_supply_temperature_c",
            unit="°C",
            sampling_interval_seconds=SAMPLING_INTERVAL_THERMAL,
            min_valid=10.0,
            max_valid=95.0,
            default_value=68.0,
            sensor_type="RTD",
            description="Heating loop main supply flow temperature",
        ),
        SensorConfig(
            sensor_id="BHARATI.HEATING.RETURN_TEMP",
            asset=asset,
            category=SensorCategory.HEATING,
            kind=SensorKind.INSTRUMENT,
            parameter="heating_return_temperature_c",
            unit="°C",
            sampling_interval_seconds=SAMPLING_INTERVAL_THERMAL,
            min_valid=10.0,
            max_valid=85.0,
            default_value=52.0,
            sensor_type="RTD",
            description="Heating loop main return flow temperature",
        ),
        SensorConfig(
            sensor_id="BHARATI.HEATING.GLYCOL_TEMP",
            asset=asset,
            category=SensorCategory.HEATING,
            kind=SensorKind.INSTRUMENT,
            parameter="glycol_temperature_c",
            unit="°C",
            sampling_interval_seconds=SAMPLING_INTERVAL_THERMAL,
            min_valid=10.0,
            max_valid=95.0,
            default_value=65.0,
            sensor_type="RTD",
            description="Hydronic glycol loop mixture temperature",
        ),
        SensorConfig(
            sensor_id="BHARATI.HEATING.GLYCOL_PRESSURE",
            asset=asset,
            category=SensorCategory.HEATING,
            kind=SensorKind.INSTRUMENT,
            parameter="glycol_pressure_bar",
            unit="bar",
            sampling_interval_seconds=SAMPLING_INTERVAL_PRESSURE,
            min_valid=0.5,
            max_valid=6.0,
            default_value=GLYCOL_LOOP_PRESSURE_NOMINAL_BAR,
            sensor_type="PRESSURE_TRANSMITTER",
            description="Glycol loop static expansion pressure",
        ),
        SensorConfig(
            sensor_id="BHARATI.HEATING.BUFFER_TANK_TEMP",
            asset=asset,
            category=SensorCategory.HEATING,
            kind=SensorKind.INSTRUMENT,
            parameter="buffer_tank_temperature_c",
            unit="°C",
            sampling_interval_seconds=SAMPLING_INTERVAL_THERMAL,
            min_valid=10.0,
            max_valid=90.0,
            default_value=64.0,
            sensor_type="RTD",
            description="Thermal buffer storage tank temperature",
        ),
        SensorConfig(
            sensor_id="BHARATI.HEATING.HOT_WATER_TEMP",
            asset=asset,
            category=SensorCategory.HEATING,
            kind=SensorKind.INSTRUMENT,
            parameter="hot_water_temperature_c",
            unit="°C",
            sampling_interval_seconds=SAMPLING_INTERVAL_THERMAL,
            min_valid=20.0,
            max_valid=80.0,
            default_value=58.0,
            sensor_type="RTD",
            description="Domestic service hot water temperature",
        ),
        SensorConfig(
            sensor_id="BHARATI.HEATING.PUMP_STATUS",
            asset=asset,
            category=SensorCategory.HEATING,
            kind=SensorKind.STATE,
            parameter="heating_pump_status",
            unit="state",
            sampling_interval_seconds=SAMPLING_INTERVAL_STATUS,
            default_value="RUNNING",
            sensor_type="STATUS_INDICATOR",
            description="Heating circulation pump operational state",
        ),
        SensorConfig(
            sensor_id="BHARATI.HEATING.PUMP_FLOW",
            asset=asset,
            category=SensorCategory.HEATING,
            kind=SensorKind.INSTRUMENT,
            parameter="heating_pump_flow",
            unit="m³/h",
            sampling_interval_seconds=SAMPLING_INTERVAL_PRESSURE,
            min_valid=0.0,
            max_valid=30.0,
            default_value=12.5,
            sensor_type="FLOW_METER",
            description="Heating circulation volumetric flow rate",
        ),
        SensorConfig(
            sensor_id="BHARATI.HEATING.PUMP_PRESSURE",
            asset=asset,
            category=SensorCategory.HEATING,
            kind=SensorKind.INSTRUMENT,
            parameter="heating_pump_pressure",
            unit="bar",
            sampling_interval_seconds=SAMPLING_INTERVAL_PRESSURE,
            min_valid=0.0,
            max_valid=6.0,
            default_value=2.4,
            sensor_type="PRESSURE_TRANSMITTER",
            description="Heating pump differential head pressure",
        ),
        SensorConfig(
            sensor_id="BHARATI.HEATING.CHP_THERMAL_KW",
            asset=asset,
            category=SensorCategory.HEATING,
            kind=SensorKind.INSTRUMENT,
            parameter="thermal_output_kw",
            unit="kWth",
            sampling_interval_seconds=SAMPLING_INTERVAL_THERMAL,
            min_valid=0.0,
            max_valid=250.0,
            default_value=0.0,
            sensor_type="CALORIMETER",
            description="Useful thermal energy extracted from CHP heat exchangers",
        ),
        # Derived heating sensors
        SensorConfig(
            sensor_id="BHARATI.HEATING.DELTA_T",
            asset=asset,
            category=SensorCategory.HEATING,
            kind=SensorKind.DERIVED,
            parameter="heating_delta_t",
            unit="°C",
            sampling_interval_seconds=SAMPLING_INTERVAL_DERIVED,
            min_valid=0.0,
            max_valid=40.0,
            default_value=16.0,
            sensor_type="CALCULATED_METRIC",
            description="Heating loop supply minus return temperature differential",
        ),
        SensorConfig(
            sensor_id="BHARATI.HEATING.ESTIMATED_THERMAL_KW",
            asset=asset,
            category=SensorCategory.HEATING,
            kind=SensorKind.DERIVED,
            parameter="estimated_thermal_output_kw",
            unit="kWth",
            sampling_interval_seconds=SAMPLING_INTERVAL_DERIVED,
            min_valid=0.0,
            max_valid=MAX_STATION_HEATING_DEMAND_KW * 1.1,
            default_value=0.0,
            sensor_type="CALCULATED_METRIC",
            description="Calculated useful thermal delivery (bounded by max station demand ~155 kWth)",
        ),
    ]


def build_virtual_sensor_configs() -> list[SensorConfig]:
    """Generate system-level virtual/derived sensor configurations."""
    asset = "STATION-ENERGY"
    return [
        SensorConfig(
            sensor_id="BHARATI.VIRTUAL.TOTAL_GENERATION",
            asset=asset,
            category=SensorCategory.VIRTUAL,
            kind=SensorKind.DERIVED,
            parameter="total_generation_kw",
            unit="kW",
            sampling_interval_seconds=SAMPLING_INTERVAL_DERIVED,
            min_valid=0.0,
            max_valid=CHP_COUNT * 105.0,
            default_value=0.0,
            sensor_type="CALCULATED_METRIC",
            description="Total active electrical power generated across running CHPs",
        ),
        SensorConfig(
            sensor_id="BHARATI.VIRTUAL.TOTAL_LOAD",
            asset=asset,
            category=SensorCategory.VIRTUAL,
            kind=SensorKind.DERIVED,
            parameter="total_station_load_kw",
            unit="kW",
            sampling_interval_seconds=SAMPLING_INTERVAL_DERIVED,
            min_valid=0.0,
            max_valid=350.0,
            default_value=175.0,
            sensor_type="CALCULATED_METRIC",
            description="Simulated total station active electrical power demand",
        ),
        SensorConfig(
            sensor_id="BHARATI.VIRTUAL.NET_BALANCE",
            asset=asset,
            category=SensorCategory.VIRTUAL,
            kind=SensorKind.DERIVED,
            parameter="net_energy_balance_kw",
            unit="kW",
            sampling_interval_seconds=SAMPLING_INTERVAL_DERIVED,
            min_valid=-100.0,
            max_valid=300.0,
            default_value=0.0,
            sensor_type="CALCULATED_METRIC",
            description="Net electrical power balance (generation minus station load)",
        ),
        SensorConfig(
            sensor_id="BHARATI.VIRTUAL.TOTAL_FUEL",
            asset=asset,
            category=SensorCategory.VIRTUAL,
            kind=SensorKind.DERIVED,
            parameter="total_fuel_l",
            unit="L",
            sampling_interval_seconds=SAMPLING_INTERVAL_DERIVED,
            min_valid=0.0,
            max_valid=(FUEL_FARM_CAPACITY_L + DAY_TANK_CAPACITY_L) * 1.05,
            default_value=275_850.0,
            sensor_type="CALCULATED_METRIC",
            description="Total station usable fuel across bulk farm and day tank",
        ),
        SensorConfig(
            sensor_id="BHARATI.VIRTUAL.FUEL_AUTONOMY",
            asset=asset,
            category=SensorCategory.VIRTUAL,
            kind=SensorKind.DERIVED,
            parameter="estimated_fuel_autonomy_hours",
            unit="h",
            sampling_interval_seconds=SAMPLING_INTERVAL_DERIVED,
            min_valid=0.0,
            max_valid=50000.0,
            default_value=6000.0,
            sensor_type="CALCULATED_METRIC",
            description="Estimated station fuel autonomy in hours",
        ),
        SensorConfig(
            sensor_id="BHARATI.VIRTUAL.GENERATOR_UTILIZATION",
            asset=asset,
            category=SensorCategory.VIRTUAL,
            kind=SensorKind.DERIVED,
            parameter="generator_utilization_percent",
            unit="%",
            sampling_interval_seconds=SAMPLING_INTERVAL_DERIVED,
            min_valid=0.0,
            max_valid=120.0,
            default_value=0.0,
            sensor_type="CALCULATED_METRIC",
            description="Generation relative to online CHP capacity",
        ),
        SensorConfig(
            sensor_id="BHARATI.VIRTUAL.TOTAL_THERMAL_OUTPUT",
            asset=asset,
            category=SensorCategory.VIRTUAL,
            kind=SensorKind.DERIVED,
            parameter="total_thermal_output_kw",
            unit="kWth",
            sampling_interval_seconds=SAMPLING_INTERVAL_DERIVED,
            min_valid=0.0,
            max_valid=MAX_STATION_HEATING_DEMAND_KW * 1.1,
            default_value=0.0,
            sensor_type="CALCULATED_METRIC",
            description="Total useful thermal output delivered for station heating",
        ),
        SensorConfig(
            sensor_id="BHARATI.VIRTUAL.HEATING_DELTA_T",
            asset=asset,
            category=SensorCategory.VIRTUAL,
            kind=SensorKind.DERIVED,
            parameter="heating_delta_t",
            unit="°C",
            sampling_interval_seconds=SAMPLING_INTERVAL_DERIVED,
            min_valid=0.0,
            max_valid=40.0,
            default_value=16.0,
            sensor_type="CALCULATED_METRIC",
            description="System-wide heating loop temperature differential",
        ),
        SensorConfig(
            sensor_id="BHARATI.VIRTUAL.CRITICAL_LOAD_PERCENT",
            asset=asset,
            category=SensorCategory.VIRTUAL,
            kind=SensorKind.DERIVED,
            parameter="critical_load_percent",
            unit="%",
            sampling_interval_seconds=SAMPLING_INTERVAL_DERIVED,
            min_valid=0.0,
            max_valid=100.0,
            default_value=30.0,
            sensor_type="CALCULATED_METRIC",
            description="Percentage of total station load supplied via UPS critical bus",
        ),
        SensorConfig(
            sensor_id="BHARATI.VIRTUAL.ELECTRICAL_EFFICIENCY",
            asset=asset,
            category=SensorCategory.VIRTUAL,
            kind=SensorKind.DERIVED,
            parameter="electrical_efficiency_percent",
            unit="%",
            sampling_interval_seconds=SAMPLING_INTERVAL_DERIVED,
            min_valid=0.0,
            max_valid=60.0,
            default_value=35.0,
            sensor_type="CALCULATED_METRIC",
            description="Electrical power output relative to fuel energy input (based on 9.89 kWh/L diesel LHV)",
        ),
        SensorConfig(
            sensor_id="BHARATI.VIRTUAL.TOTAL_EFFICIENCY",
            asset=asset,
            category=SensorCategory.VIRTUAL,
            kind=SensorKind.DERIVED,
            parameter="total_chp_efficiency_percent",
            unit="%",
            sampling_interval_seconds=SAMPLING_INTERVAL_DERIVED,
            min_valid=0.0,
            max_valid=95.0,
            default_value=75.0,
            sensor_type="CALCULATED_METRIC",
            description="Combined CHP efficiency (electrical + useful thermal relative to fuel energy input)",
        ),
    ]
