"""Configuration specifications, asset registry, and sensor catalogue for Bharati Logistics.

Part of SIH 2026 Project SIH26060: F.R.I.D.A.Y.
Digital Platform for Efficient Remote Management of Indian Antarctic Research Stations.
Target: Bharati Research Station, Larsemann Hills, East Antarctica.

Defines:
- 16 physical fleet assets in FLEET_ASSET_REGISTRY
- Exactly 98 configured logistics observation points across 11 domains
- Formal anti-duplication rule preventing environmental observation duplication
"""

from __future__ import annotations

from typing import Any

from .models import (
    EvidenceLevel,
    FailureType,
    FleetAssetInfo,
    LogisticsDomain,
    PhysicalQuantity,
    SensorConfig,
    SensorKind,
)

SOURCE_REFERENCE_DEFAULT = "bharati_logistics_physics_v1"

# Standard confidence mappings aligned with Energy, Infrastructure, and Environment
CONFIDENCE_BY_EVIDENCE: dict[EvidenceLevel, float] = {
    EvidenceLevel.DOCUMENTED: 1.0,
    EvidenceLevel.IMPLIED: 0.8,
    EvidenceLevel.DERIVED: 0.85,
    EvidenceLevel.NOT_PUBLICLY_CONFIRMED: 0.65,
}


def get_confidence_for_evidence(evidence_level: EvidenceLevel) -> float:
    """Return confidence score corresponding to the evidence level."""
    return CONFIDENCE_BY_EVIDENCE.get(evidence_level, 0.7)


# ==============================================================================
# BHARATI FLEET ASSET REGISTRY (16 Documented Physical Machines)
# ==============================================================================

FLEET_ASSET_REGISTRY: dict[str, FleetAssetInfo] = {
    "PB-01": FleetAssetInfo(
        asset_id="PB-01",
        name="PistenBully 300 Polar Lead Groomer/Hauler",
        asset_type="PISTEN_BULLY",
        capacity_description="Heavy snow grooming and sled hauling up to 20t",
        documented_model="Kässbohrer PistenBully 300 Polar",
        operational_role="PRIMARY_HAULER",
    ),
    "PB-02": FleetAssetInfo(
        asset_id="PB-02",
        name="PistenBully 300 Polar Support Hauler",
        asset_type="PISTEN_BULLY",
        capacity_description="Heavy snow grooming and cargo transport",
        documented_model="Kässbohrer PistenBully 300 Polar",
        operational_role="SUPPORT_HAULER",
    ),
    "PB-03": FleetAssetInfo(
        asset_id="PB-03",
        name="PistenBully 100 Passenger Transport",
        asset_type="PISTEN_BULLY",
        capacity_description="Personnel transport cabin and field support",
        documented_model="Kässbohrer PistenBully 100",
        operational_role="PERSONNEL_TRANSPORT",
    ),
    "PB-04": FleetAssetInfo(
        asset_id="PB-04",
        name="PistenBully 100 Utility Tracked Carrier",
        asset_type="PISTEN_BULLY",
        capacity_description="Route maintenance and field science deployment",
        documented_model="Kässbohrer PistenBully 100",
        operational_role="UTILITY_CARRIER",
    ),
    "PB-05": FleetAssetInfo(
        asset_id="PB-05",
        name="PistenBully 300 Polar Standby Sled",
        asset_type="PISTEN_BULLY",
        capacity_description="Heavy transport standby and deep field backup",
        documented_model="Kässbohrer PistenBully 300 Polar",
        operational_role="STANDBY_HAULER",
    ),
    "PB-06": FleetAssetInfo(
        asset_id="PB-06",
        name="PistenBully Reserve Vehicle",
        asset_type="PISTEN_BULLY",
        capacity_description="Reserve chassis and winter maintenance",
        documented_model="Kässbohrer PistenBully 300 Polar",
        operational_role="RESERVE_MAINTENANCE",
    ),
    "SC-01": FleetAssetInfo(
        asset_id="SC-01",
        name="Snow Scooter Scout 01",
        asset_type="SNOW_SCOOTER",
        capacity_description="Fast route reconnaissance and local transfer (2 pax)",
        documented_model="Yamaha / Ski-Doo Utility Snowmobile",
        operational_role="FAST_RECON",
    ),
    "SC-02": FleetAssetInfo(
        asset_id="SC-02",
        name="Snow Scooter Scout 02",
        asset_type="SNOW_SCOOTER",
        capacity_description="Fast route reconnaissance and science transport",
        documented_model="Yamaha / Ski-Doo Utility Snowmobile",
        operational_role="FAST_RECON",
    ),
    "SC-03": FleetAssetInfo(
        asset_id="SC-03",
        name="Snow Scooter Field Patrol 03",
        asset_type="SNOW_SCOOTER",
        capacity_description="Field camp safety and emergency response",
        documented_model="Yamaha / Ski-Doo Utility Snowmobile",
        operational_role="FIELD_PATROL",
    ),
    "SC-04": FleetAssetInfo(
        asset_id="SC-04",
        name="Snow Scooter Standby 04",
        asset_type="SNOW_SCOOTER",
        capacity_description="Station perimeter utility and backup",
        documented_model="Yamaha / Ski-Doo Utility Snowmobile",
        operational_role="STANDBY_SCOOTER",
    ),
    "TELEHANDLER-01": FleetAssetInfo(
        asset_id="TELEHANDLER-01",
        name="Telescopic Material Handler",
        asset_type="TELEHANDLER",
        capacity_description="Container yard handling and heavy cargo pallet lifting (4t)",
        documented_model="Manitou / JCB Rough-Terrain Telehandler",
        operational_role="YARD_MATERIAL_HANDLING",
    ),
    "EXCAVATOR-01": FleetAssetInfo(
        asset_id="EXCAVATOR-01",
        name="Heavy Tracked Excavator 01",
        asset_type="EXCAVATOR",
        capacity_description="Earthmoving, snow clearing, and pipeline trenching (20t)",
        documented_model="Komatsu / Caterpillar Heavy Excavator",
        operational_role="HEAVY_EARTHMOVING",
    ),
    "EXCAVATOR-02": FleetAssetInfo(
        asset_id="EXCAVATOR-02",
        name="Heavy Tracked Excavator 02",
        asset_type="EXCAVATOR",
        capacity_description="Coastal loading site and infrastructure support (20t)",
        documented_model="Komatsu / Caterpillar Heavy Excavator",
        operational_role="COASTAL_SITE_SUPPORT",
    ),
    "BULLDOZER-01": FleetAssetInfo(
        asset_id="BULLDOZER-01",
        name="Crawler Bulldozer 01",
        asset_type="BULLDOZER",
        capacity_description="Heavy snow berm clearance, road grading, and towing",
        documented_model="Komatsu / Caterpillar D65 Tracked Dozer",
        operational_role="SNOW_ROAD_GRADING",
    ),
    "MANTIS-01": FleetAssetInfo(
        asset_id="MANTIS-01",
        name="Mantis Crawler Crane 01",
        asset_type="MANTIS_CRANE",
        capacity_description="Rough-terrain container discharge and module placement (35t)",
        documented_model="Tadano Mantis 15010 Telescopic Crawler Crane",
        operational_role="CONTAINER_DISCHARGE",
    ),
    "MANTIS-02": FleetAssetInfo(
        asset_id="MANTIS-02",
        name="Mantis Crawler Crane 02",
        asset_type="MANTIS_CRANE",
        capacity_description="Station assembly, heavy lifting, and fuel tank handling",
        documented_model="Tadano Mantis 15010 Telescopic Crawler Crane",
        operational_role="STATION_HEAVY_LIFT",
    ),
}


# ==============================================================================
# SENSOR CATALOGUE: EXACTLY 98 OBSERVATION POINTS ACROSS 11 DOMAINS
# ==============================================================================

BHARATI_LOGISTICS_SENSORS: list[SensorConfig] = [
    # --------------------------------------------------------------------------
    # 1. FLEET & VEHICLE TELEMETRY (16 Points)
    # --------------------------------------------------------------------------
    SensorConfig(
        sensor_id="LOG-FLEET-PB01-SPEED",
        name="PistenBully 01 Ground Speed",
        asset_id="PB-01",
        domain=LogisticsDomain.FLEET,
        subsystem="fleet_pb01",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.NOT_PUBLICLY_CONFIRMED,
        physical_quantity=PhysicalQuantity.SPEED,
        unit="km_h",
        sampling_interval_seconds=1.0,
        location_scope="LOCAL_FLEET",
        measurement_zone="FIELD_TRACK",
        min_value=0.0,
        max_value=40.0,
        default_value=0.0,
        state_path="fleet.pb01.speed_km_h",
        description="Simulated vehicle GPS/speedometer ground speed for PB-01",
        simulation_assumption=True,
    ),
    SensorConfig(
        sensor_id="LOG-FLEET-PB01-HEADING",
        name="PistenBully 01 Compass Heading",
        asset_id="PB-01",
        domain=LogisticsDomain.FLEET,
        subsystem="fleet_pb01",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.NOT_PUBLICLY_CONFIRMED,
        physical_quantity=PhysicalQuantity.HEADING,
        unit="deg",
        sampling_interval_seconds=1.0,
        location_scope="LOCAL_FLEET",
        measurement_zone="FIELD_TRACK",
        min_value=0.0,
        max_value=360.0,
        default_value=0.0,
        state_path="fleet.pb01.heading_deg",
        description="Simulated compass heading angle for PB-01",
        simulation_assumption=True,
    ),
    SensorConfig(
        sensor_id="LOG-FLEET-PB01-RPM",
        name="PistenBully 01 Engine Speed",
        asset_id="PB-01",
        domain=LogisticsDomain.FLEET,
        subsystem="fleet_pb01",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.NOT_PUBLICLY_CONFIRMED,
        physical_quantity=PhysicalQuantity.ROTATIONAL_SPEED,
        unit="RPM",
        sampling_interval_seconds=1.0,
        location_scope="LOCAL_FLEET",
        measurement_zone="FIELD_TRACK",
        min_value=0.0,
        max_value=3000.0,
        default_value=0.0,
        state_path="fleet.pb01.engine_rpm",
        description="Simulated CAN-bus diesel engine rotational speed for PB-01",
        simulation_assumption=True,
    ),
    SensorConfig(
        sensor_id="LOG-FLEET-PB01-ENG-TEMP",
        name="PistenBully 01 Engine Coolant Temperature",
        asset_id="PB-01",
        domain=LogisticsDomain.FLEET,
        subsystem="fleet_pb01",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.NOT_PUBLICLY_CONFIRMED,
        physical_quantity=PhysicalQuantity.TEMPERATURE,
        unit="degC",
        sampling_interval_seconds=5.0,
        location_scope="LOCAL_FLEET",
        measurement_zone="FIELD_TRACK",
        min_value=-40.0,
        max_value=120.0,
        default_value=-10.0,
        state_path="fleet.pb01.engine_temp_c",
        description="Simulated diesel engine coolant temperature for PB-01",
        simulation_assumption=True,
    ),
    SensorConfig(
        sensor_id="LOG-FLEET-PB01-FUEL-LVL",
        name="PistenBully 01 Fuel Level",
        asset_id="PB-01",
        domain=LogisticsDomain.FLEET,
        subsystem="fleet_pb01",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.NOT_PUBLICLY_CONFIRMED,
        physical_quantity=PhysicalQuantity.PERCENT,
        unit="%",
        sampling_interval_seconds=10.0,
        location_scope="LOCAL_FLEET",
        measurement_zone="FIELD_TRACK",
        min_value=0.0,
        max_value=100.0,
        default_value=85.0,
        state_path="fleet.pb01.fuel_level_percent",
        description="Simulated fuel tank gauge level percentage for PB-01",
        simulation_assumption=True,
    ),
    SensorConfig(
        sensor_id="LOG-FLEET-PB01-FUEL-RATE",
        name="PistenBully 01 Fuel Consumption Rate",
        asset_id="PB-01",
        domain=LogisticsDomain.FLEET,
        subsystem="fleet_pb01",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.NOT_PUBLICLY_CONFIRMED,
        physical_quantity=PhysicalQuantity.FLOW_RATE,
        unit="L_h",
        sampling_interval_seconds=5.0,
        location_scope="LOCAL_FLEET",
        measurement_zone="FIELD_TRACK",
        min_value=0.0,
        max_value=60.0,
        default_value=0.0,
        state_path="fleet.pb01.fuel_rate_l_h",
        description="Simulated instantaneous fuel consumption rate for PB-01",
        simulation_assumption=True,
    ),
    SensorConfig(
        sensor_id="LOG-FLEET-PB01-BATTERY",
        name="PistenBully 01 Electrical System Voltage",
        asset_id="PB-01",
        domain=LogisticsDomain.FLEET,
        subsystem="fleet_pb01",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.NOT_PUBLICLY_CONFIRMED,
        physical_quantity=PhysicalQuantity.VOLTAGE,
        unit="V",
        sampling_interval_seconds=10.0,
        location_scope="LOCAL_FLEET",
        measurement_zone="FIELD_TRACK",
        min_value=0.0,
        max_value=32.0,
        default_value=24.0,
        state_path="fleet.pb01.battery_voltage_v",
        description="Simulated 24V starting and electronics battery voltage for PB-01",
        simulation_assumption=True,
    ),
    SensorConfig(
        sensor_id="LOG-FLEET-PB01-ENG-HOURS",
        name="PistenBully 01 Cumulative Engine Hours",
        asset_id="PB-01",
        domain=LogisticsDomain.FLEET,
        subsystem="fleet_pb01",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.NOT_PUBLICLY_CONFIRMED,
        physical_quantity=PhysicalQuantity.TIME,
        unit="h",
        sampling_interval_seconds=60.0,
        location_scope="LOCAL_FLEET",
        measurement_zone="FIELD_TRACK",
        min_value=0.0,
        max_value=50000.0,
        default_value=1240.0,
        state_path="fleet.pb01.engine_hours",
        description="Simulated total accumulated operational run hours for PB-01",
        simulation_assumption=True,
    ),
    SensorConfig(
        sensor_id="LOG-FLEET-PB01-STATUS",
        name="PistenBully 01 Operational Status",
        asset_id="PB-01",
        domain=LogisticsDomain.FLEET,
        subsystem="fleet_pb01",
        kind=SensorKind.STATE,
        evidence_level=EvidenceLevel.DOCUMENTED,
        physical_quantity=PhysicalQuantity.STATUS,
        unit="status",
        sampling_interval_seconds=5.0,
        location_scope="LOCAL_FLEET",
        measurement_zone="FIELD_TRACK",
        default_value="STANDBY",
        state_path="fleet.pb01.status",
        description="Operational state of lead PistenBully PB-01 (READY, ACTIVE, STANDBY, MAINTENANCE)",
    ),
    SensorConfig(
        sensor_id="LOG-FLEET-PB02-STATUS",
        name="PistenBully 02 Operational Status",
        asset_id="PB-02",
        domain=LogisticsDomain.FLEET,
        subsystem="fleet_pb02",
        kind=SensorKind.STATE,
        evidence_level=EvidenceLevel.DOCUMENTED,
        physical_quantity=PhysicalQuantity.STATUS,
        unit="status",
        sampling_interval_seconds=10.0,
        location_scope="LOCAL_FLEET",
        measurement_zone="GARAGE",
        default_value="STANDBY",
        state_path="fleet.pb02.status",
        description="Operational state of support PistenBully PB-02",
    ),
    SensorConfig(
        sensor_id="LOG-FLEET-SC01-STATUS",
        name="Snow Scooter 01 Operational Status",
        asset_id="SC-01",
        domain=LogisticsDomain.FLEET,
        subsystem="fleet_sc01",
        kind=SensorKind.STATE,
        evidence_level=EvidenceLevel.DOCUMENTED,
        physical_quantity=PhysicalQuantity.STATUS,
        unit="status",
        sampling_interval_seconds=10.0,
        location_scope="LOCAL_FLEET",
        measurement_zone="GARAGE",
        default_value="READY",
        state_path="fleet.sc01.status",
        description="Operational state of snow scooter SC-01",
    ),
    SensorConfig(
        sensor_id="LOG-FLEET-SC01-FUEL",
        name="Snow Scooter 01 Fuel Level",
        asset_id="SC-01",
        domain=LogisticsDomain.FLEET,
        subsystem="fleet_sc01",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.NOT_PUBLICLY_CONFIRMED,
        physical_quantity=PhysicalQuantity.PERCENT,
        unit="%",
        sampling_interval_seconds=30.0,
        location_scope="LOCAL_FLEET",
        measurement_zone="GARAGE",
        min_value=0.0,
        max_value=100.0,
        default_value=90.0,
        state_path="fleet.sc01.fuel_level_percent",
        description="Simulated fuel level percentage for snow scooter SC-01",
        simulation_assumption=True,
    ),
    SensorConfig(
        sensor_id="LOG-FLEET-TH01-HYD-PRESS",
        name="Telehandler Hydraulic System Pressure",
        asset_id="TELEHANDLER-01",
        domain=LogisticsDomain.FLEET,
        subsystem="fleet_telehandler",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.NOT_PUBLICLY_CONFIRMED,
        physical_quantity=PhysicalQuantity.PRESSURE,
        unit="bar",
        sampling_interval_seconds=5.0,
        location_scope="LOCAL_FLEET",
        measurement_zone="CONTAINER_YARD",
        min_value=0.0,
        max_value=350.0,
        default_value=210.0,
        state_path="fleet.telehandler.hydraulic_pressure_bar",
        description="Simulated hydraulic circuit pressure for rough-terrain telehandler",
        simulation_assumption=True,
    ),
    SensorConfig(
        sensor_id="LOG-FLEET-TH01-STATUS",
        name="Telehandler Operational Status",
        asset_id="TELEHANDLER-01",
        domain=LogisticsDomain.FLEET,
        subsystem="fleet_telehandler",
        kind=SensorKind.STATE,
        evidence_level=EvidenceLevel.DOCUMENTED,
        physical_quantity=PhysicalQuantity.STATUS,
        unit="status",
        sampling_interval_seconds=10.0,
        location_scope="LOCAL_FLEET",
        measurement_zone="CONTAINER_YARD",
        default_value="READY",
        state_path="fleet.telehandler.status",
        description="Operational state of rough-terrain telehandler",
    ),
    SensorConfig(
        sensor_id="LOG-FLEET-EXC01-STATUS",
        name="Heavy Excavator 01 Operational Status",
        asset_id="EXCAVATOR-01",
        domain=LogisticsDomain.FLEET,
        subsystem="fleet_excavator",
        kind=SensorKind.STATE,
        evidence_level=EvidenceLevel.DOCUMENTED,
        physical_quantity=PhysicalQuantity.STATUS,
        unit="status",
        sampling_interval_seconds=10.0,
        location_scope="LOCAL_FLEET",
        measurement_zone="STATION_PERIMETER",
        default_value="STANDBY",
        state_path="fleet.excavator.status",
        description="Operational state of heavy tracked excavator EXCAVATOR-01",
    ),
    SensorConfig(
        sensor_id="LOG-FLEET-CRANE01-STATUS",
        name="Mantis Crawler Crane 01 Operational Status",
        asset_id="MANTIS-01",
        domain=LogisticsDomain.FLEET,
        subsystem="fleet_crane",
        kind=SensorKind.STATE,
        evidence_level=EvidenceLevel.DOCUMENTED,
        physical_quantity=PhysicalQuantity.STATUS,
        unit="status",
        sampling_interval_seconds=10.0,
        location_scope="LOCAL_FLEET",
        measurement_zone="CARGO_STAGING",
        default_value="READY",
        state_path="fleet.mantis_crane.status",
        description="Operational state of Mantis crawler crane 01",
    ),

    # --------------------------------------------------------------------------
    # 2. CARGO & CONTAINERS (10 Points)
    # --------------------------------------------------------------------------
    SensorConfig(
        sensor_id="LOG-CARGO-TOTAL-COUNT",
        name="Station Total Container Units Stored",
        asset_id="CONTAINER_YARD",
        domain=LogisticsDomain.CARGO,
        subsystem="cargo_yard",
        kind=SensorKind.STATE,
        evidence_level=EvidenceLevel.DOCUMENTED,
        physical_quantity=PhysicalQuantity.COUNT,
        unit="count",
        sampling_interval_seconds=60.0,
        location_scope="STATION_STORAGE",
        measurement_zone="CONTAINER_YARD",
        min_value=0.0,
        max_value=1000.0,
        default_value=64.0,
        state_path="cargo.total_cargo_units",
        description="Documented inventory record of ISO containers in station yard",
    ),
    SensorConfig(
        sensor_id="LOG-CARGO-IN-TRANSIT",
        name="Cargo Units In Transit",
        asset_id="CARGO_LOGISTICS",
        domain=LogisticsDomain.CARGO,
        subsystem="cargo_transit",
        kind=SensorKind.STATE,
        evidence_level=EvidenceLevel.DOCUMENTED,
        physical_quantity=PhysicalQuantity.COUNT,
        unit="count",
        sampling_interval_seconds=60.0,
        location_scope="STATION_STORAGE",
        measurement_zone="FIELD_TRACK",
        min_value=0.0,
        max_value=500.0,
        default_value=0.0,
        state_path="cargo.in_transit_units",
        description="Active shipment manifests for cargo currently on sleds or barges",
    ),
    SensorConfig(
        sensor_id="LOG-CARGO-C01-LOC",
        name="Container 01 Storage Location Zone",
        asset_id="CONTAINER-01",
        domain=LogisticsDomain.CARGO,
        subsystem="cargo_c01",
        kind=SensorKind.STATE,
        evidence_level=EvidenceLevel.NOT_PUBLICLY_CONFIRMED,
        physical_quantity=PhysicalQuantity.STATUS,
        unit="status",
        sampling_interval_seconds=30.0,
        location_scope="STATION_STORAGE",
        measurement_zone="CONTAINER_YARD",
        default_value="YARD_ZONE_A",
        state_path="cargo.c01.location_zone",
        description="Simulated physical yard zoning coordinate for tracked container C01",
        simulation_assumption=True,
    ),
    SensorConfig(
        sensor_id="LOG-CARGO-C01-WEIGHT",
        name="Container 01 Manifest Gross Weight",
        asset_id="CONTAINER-01",
        domain=LogisticsDomain.CARGO,
        subsystem="cargo_c01",
        kind=SensorKind.STATE,
        evidence_level=EvidenceLevel.DOCUMENTED,
        physical_quantity=PhysicalQuantity.MASS,
        unit="kg",
        sampling_interval_seconds=60.0,
        location_scope="STATION_STORAGE",
        measurement_zone="CONTAINER_YARD",
        min_value=0.0,
        max_value=35000.0,
        default_value=12500.0,
        state_path="cargo.c01.gross_weight_kg",
        description="Documented manifest gross weight record for container C01",
    ),
    SensorConfig(
        sensor_id="LOG-CARGO-C01-TEMP",
        name="Container 01 Internal Ambient Temperature",
        asset_id="CONTAINER-01",
        domain=LogisticsDomain.CARGO,
        subsystem="cargo_c01",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.NOT_PUBLICLY_CONFIRMED,
        physical_quantity=PhysicalQuantity.TEMPERATURE,
        unit="degC",
        sampling_interval_seconds=10.0,
        location_scope="STATION_STORAGE",
        measurement_zone="CONTAINER_YARD",
        min_value=-50.0,
        max_value=40.0,
        default_value=-8.0,
        state_path="cargo.c01.temperature_c",
        description="Simulated IoT internal temperature sensor for dry goods container C01",
        simulation_assumption=True,
    ),
    SensorConfig(
        sensor_id="LOG-CARGO-C01-HUM",
        name="Container 01 Internal Relative Humidity",
        asset_id="CONTAINER-01",
        domain=LogisticsDomain.CARGO,
        subsystem="cargo_c01",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.NOT_PUBLICLY_CONFIRMED,
        physical_quantity=PhysicalQuantity.PERCENT,
        unit="%",
        sampling_interval_seconds=30.0,
        location_scope="STATION_STORAGE",
        measurement_zone="CONTAINER_YARD",
        min_value=0.0,
        max_value=100.0,
        default_value=45.0,
        state_path="cargo.c01.relative_humidity_percent",
        description="Simulated IoT relative humidity sensor inside container C01",
        simulation_assumption=True,
    ),
    SensorConfig(
        sensor_id="LOG-CARGO-C01-SHOCK",
        name="Container 01 Impact Shock Sensor",
        asset_id="CONTAINER-01",
        domain=LogisticsDomain.CARGO,
        subsystem="cargo_c01",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.NOT_PUBLICLY_CONFIRMED,
        physical_quantity=PhysicalQuantity.ACCELERATION,
        unit="g",
        sampling_interval_seconds=1.0,
        location_scope="STATION_STORAGE",
        measurement_zone="CONTAINER_YARD",
        min_value=0.0,
        max_value=20.0,
        default_value=0.05,
        state_path="cargo.c01.shock_g",
        description="Simulated 3-axis peak shock accelerometer for handling integrity",
        simulation_assumption=True,
    ),
    SensorConfig(
        sensor_id="LOG-CARGO-C01-TILT",
        name="Container 01 Incline Tilt Sensor",
        asset_id="CONTAINER-01",
        domain=LogisticsDomain.CARGO,
        subsystem="cargo_c01",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.NOT_PUBLICLY_CONFIRMED,
        physical_quantity=PhysicalQuantity.DIMENSIONLESS,
        unit="deg",
        sampling_interval_seconds=5.0,
        location_scope="STATION_STORAGE",
        measurement_zone="CONTAINER_YARD",
        min_value=0.0,
        max_value=90.0,
        default_value=0.8,
        state_path="cargo.c01.tilt_deg",
        description="Simulated inclinometer measuring container levelling tilt angle",
        simulation_assumption=True,
    ),
    SensorConfig(
        sensor_id="LOG-CARGO-C01-DOOR",
        name="Container 01 Door Seal Status",
        asset_id="CONTAINER-01",
        domain=LogisticsDomain.CARGO,
        subsystem="cargo_c01",
        kind=SensorKind.STATE,
        evidence_level=EvidenceLevel.NOT_PUBLICLY_CONFIRMED,
        physical_quantity=PhysicalQuantity.STATUS,
        unit="status",
        sampling_interval_seconds=5.0,
        location_scope="STATION_STORAGE",
        measurement_zone="CONTAINER_YARD",
        default_value="CLOSED_LOCKED",
        state_path="cargo.c01.door_status",
        description="Simulated magnetic reed door contact state (CLOSED_LOCKED, OPEN)",
        simulation_assumption=True,
    ),
    SensorConfig(
        sensor_id="LOG-CARGO-HAZMAT-STATUS",
        name="Hazardous Material Staging Status",
        asset_id="HAZMAT_STAGING",
        domain=LogisticsDomain.CARGO,
        subsystem="cargo_hazmat",
        kind=SensorKind.STATE,
        evidence_level=EvidenceLevel.DOCUMENTED,
        physical_quantity=PhysicalQuantity.STATUS,
        unit="status",
        sampling_interval_seconds=60.0,
        location_scope="STATION_STORAGE",
        measurement_zone="HAZMAT_ZONE",
        default_value="CONTAINED_SECURE",
        state_path="cargo.hazmat_staging_status",
        description="Operational compliance state of station hazardous goods staging",
    ),

    # --------------------------------------------------------------------------
    # 3. FUEL LOGISTICS (10 Points)
    # --------------------------------------------------------------------------
    SensorConfig(
        sensor_id="LOG-FUEL-HELI-SUPPLY-LVL",
        name="Helicopter Aviation Fuel Supply Context Level",
        asset_id="HELI_REFUELING",
        domain=LogisticsDomain.FUEL,
        subsystem="fuel_heli_supply",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.NOT_PUBLICLY_CONFIRMED,
        physical_quantity=PhysicalQuantity.VOLUME,
        unit="L",
        sampling_interval_seconds=30.0,
        location_scope="STATION_FUEL_FARM",
        measurement_zone="HELIPAD_REFUEL",
        min_value=0.0,
        max_value=25000.0,
        default_value=18500.0,
        state_path="fuel.heli_supply_level_l",
        description="Aviation fuel staging supply volume for expedition helicopter operations",
        simulation_assumption=True,
    ),
    SensorConfig(
        sensor_id="LOG-FUEL-HELI-SUPPLY-PCT",
        name="Helicopter Aviation Fuel Supply Percentage",
        asset_id="HELI_REFUELING",
        domain=LogisticsDomain.FUEL,
        subsystem="fuel_heli_supply",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.NOT_PUBLICLY_CONFIRMED,
        physical_quantity=PhysicalQuantity.PERCENT,
        unit="%",
        sampling_interval_seconds=30.0,
        location_scope="STATION_FUEL_FARM",
        measurement_zone="HELIPAD_REFUEL",
        min_value=0.0,
        max_value=100.0,
        default_value=74.0,
        state_path="fuel.heli_supply_percent",
        description="Aviation fuel staging supply percentage",
        simulation_assumption=True,
    ),
    SensorConfig(
        sensor_id="LOG-FUEL-VEH-TANK-LVL",
        name="Vehicle Dispensing Tank Level",
        asset_id="FUEL_DISPENSER",
        domain=LogisticsDomain.FUEL,
        subsystem="fuel_dispenser",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.DOCUMENTED,
        physical_quantity=PhysicalQuantity.VOLUME,
        unit="L",
        sampling_interval_seconds=10.0,
        location_scope="STATION_FUEL_FARM",
        measurement_zone="FUEL_STATION",
        min_value=0.0,
        max_value=50000.0,
        default_value=38500.0,
        state_path="fuel.vehicle_tank_level_l",
        description="Documented ATF bulk storage tank for station fleet dispensing",
    ),
    SensorConfig(
        sensor_id="LOG-FUEL-VEH-TANK-PCT",
        name="Vehicle Dispensing Tank Percentage",
        asset_id="FUEL_DISPENSER",
        domain=LogisticsDomain.FUEL,
        subsystem="fuel_dispenser",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.DOCUMENTED,
        physical_quantity=PhysicalQuantity.PERCENT,
        unit="%",
        sampling_interval_seconds=10.0,
        location_scope="STATION_FUEL_FARM",
        measurement_zone="FUEL_STATION",
        min_value=0.0,
        max_value=100.0,
        default_value=77.0,
        state_path="fuel.vehicle_tank_percent",
        description="Documented vehicle fuel storage percentage",
    ),
    SensorConfig(
        sensor_id="LOG-FUEL-LINE-TEMP",
        name="Fuel Transfer Line Temperature",
        asset_id="FUEL_TRANSFER_LINE",
        domain=LogisticsDomain.FUEL,
        subsystem="fuel_transfer",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.IMPLIED,
        physical_quantity=PhysicalQuantity.TEMPERATURE,
        unit="degC",
        sampling_interval_seconds=10.0,
        location_scope="STATION_FUEL_FARM",
        measurement_zone="FUEL_PIPELINE",
        min_value=-50.0,
        max_value=40.0,
        default_value=-5.0,
        state_path="fuel.line_temperature_c",
        description="Heat-traced fuel transfer line fluid temperature",
    ),
    SensorConfig(
        sensor_id="LOG-FUEL-LINE-PRESS",
        name="Fuel Transfer Line Pressure",
        asset_id="FUEL_TRANSFER_LINE",
        domain=LogisticsDomain.FUEL,
        subsystem="fuel_transfer",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.IMPLIED,
        physical_quantity=PhysicalQuantity.PRESSURE,
        unit="bar",
        sampling_interval_seconds=2.0,
        location_scope="STATION_FUEL_FARM",
        measurement_zone="FUEL_PIPELINE",
        min_value=0.0,
        max_value=25.0,
        default_value=4.2,
        state_path="fuel.line_pressure_bar",
        description="Fluid pressure sensor in fuel distribution and dispensing manifold",
    ),
    SensorConfig(
        sensor_id="LOG-FUEL-TRANSFER-FLOW",
        name="Fuel Dispensing Transfer Flow Rate",
        asset_id="FUEL_DISPENSER",
        domain=LogisticsDomain.FUEL,
        subsystem="fuel_dispenser",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.NOT_PUBLICLY_CONFIRMED,
        physical_quantity=PhysicalQuantity.FLOW_RATE,
        unit="L_min",
        sampling_interval_seconds=1.0,
        location_scope="STATION_FUEL_FARM",
        measurement_zone="FUEL_STATION",
        min_value=0.0,
        max_value=300.0,
        default_value=0.0,
        state_path="fuel.transfer_flow_l_min",
        description="Volumetric positive-displacement flowmeter during vehicle refuelling",
        simulation_assumption=True,
    ),
    SensorConfig(
        sensor_id="LOG-FUEL-DISPENSED-DAILY",
        name="Cumulative Daily Fuel Dispensed to Fleet",
        asset_id="FUEL_DISPENSER",
        domain=LogisticsDomain.FUEL,
        subsystem="fuel_dispenser",
        kind=SensorKind.STATE,
        evidence_level=EvidenceLevel.DOCUMENTED,
        physical_quantity=PhysicalQuantity.VOLUME,
        unit="L",
        sampling_interval_seconds=60.0,
        location_scope="STATION_FUEL_FARM",
        measurement_zone="FUEL_STATION",
        min_value=0.0,
        max_value=5000.0,
        default_value=320.0,
        state_path="fuel.daily_dispensed_l",
        description="Operational daily log of fuel issued to Pisten Bullies and equipment",
    ),
    SensorConfig(
        sensor_id="LOG-FUEL-LEAK-MONITOR",
        name="Fuel Containment Sump Leak Detection State",
        asset_id="FUEL_DISPENSER",
        domain=LogisticsDomain.FUEL,
        subsystem="fuel_safety",
        kind=SensorKind.STATE,
        evidence_level=EvidenceLevel.IMPLIED,
        physical_quantity=PhysicalQuantity.STATUS,
        unit="status",
        sampling_interval_seconds=5.0,
        location_scope="STATION_FUEL_FARM",
        measurement_zone="FUEL_BUND",
        default_value="NORMAL",
        state_path="fuel.leak_status",
        description="Hydrocarbon optical sensor state for secondary bund containment",
    ),
    SensorConfig(
        sensor_id="LOG-FUEL-DISP-STATUS",
        name="Vehicle Dispenser Operational Status",
        asset_id="FUEL_DISPENSER",
        domain=LogisticsDomain.FUEL,
        subsystem="fuel_dispenser",
        kind=SensorKind.STATE,
        evidence_level=EvidenceLevel.DOCUMENTED,
        physical_quantity=PhysicalQuantity.STATUS,
        unit="status",
        sampling_interval_seconds=10.0,
        location_scope="STATION_FUEL_FARM",
        measurement_zone="FUEL_STATION",
        default_value="READY",
        state_path="fuel.dispenser_status",
        description="Dispenser pump electrical status (READY, DISPENSING, DISABLED, FAULT)",
    ),

    # --------------------------------------------------------------------------
    # 4. COLD CHAIN / REEFER CONTAINERS (8 Points)
    # --------------------------------------------------------------------------
    SensorConfig(
        sensor_id="LOG-REEFER-01-TEMP",
        name="Reefer 01 Core Internal Temperature",
        asset_id="REEFER-01",
        domain=LogisticsDomain.COLD_CHAIN,
        subsystem="cold_chain_r01",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.NOT_PUBLICLY_CONFIRMED,
        physical_quantity=PhysicalQuantity.TEMPERATURE,
        unit="degC",
        sampling_interval_seconds=10.0,
        location_scope="STATION_REEFER",
        measurement_zone="REEFER_YARD",
        min_value=-40.0,
        max_value=20.0,
        default_value=-22.0,
        state_path="cold_chain.reefer01.core_temp_c",
        description="Calibrated Pt100 RTD measuring frozen rations temperature inside Reefer 01",
        simulation_assumption=True,
    ),
    SensorConfig(
        sensor_id="LOG-REEFER-01-SETPOINT",
        name="Reefer 01 Temperature Setpoint",
        asset_id="REEFER-01",
        domain=LogisticsDomain.COLD_CHAIN,
        subsystem="cold_chain_r01",
        kind=SensorKind.STATE,
        evidence_level=EvidenceLevel.DOCUMENTED,
        physical_quantity=PhysicalQuantity.TEMPERATURE,
        unit="degC",
        sampling_interval_seconds=60.0,
        location_scope="STATION_REEFER",
        measurement_zone="REEFER_YARD",
        min_value=-40.0,
        max_value=10.0,
        default_value=-22.0,
        state_path="cold_chain.reefer01.setpoint_c",
        description="Thermostatic target setpoint configured for refrigerated container",
    ),
    SensorConfig(
        sensor_id="LOG-REEFER-01-DOOR",
        name="Reefer 01 Access Door Status",
        asset_id="REEFER-01",
        domain=LogisticsDomain.COLD_CHAIN,
        subsystem="cold_chain_r01",
        kind=SensorKind.STATE,
        evidence_level=EvidenceLevel.NOT_PUBLICLY_CONFIRMED,
        physical_quantity=PhysicalQuantity.STATUS,
        unit="status",
        sampling_interval_seconds=5.0,
        location_scope="STATION_REEFER",
        measurement_zone="REEFER_YARD",
        default_value="CLOSED",
        state_path="cold_chain.reefer01.door_status",
        description="Cold room door switch state (CLOSED, OPEN)",
        simulation_assumption=True,
    ),
    SensorConfig(
        sensor_id="LOG-REEFER-01-COMP-RUN",
        name="Reefer 01 Compressor Operating Status",
        asset_id="REEFER-01",
        domain=LogisticsDomain.COLD_CHAIN,
        subsystem="cold_chain_r01",
        kind=SensorKind.STATE,
        evidence_level=EvidenceLevel.NOT_PUBLICLY_CONFIRMED,
        physical_quantity=PhysicalQuantity.STATUS,
        unit="status",
        sampling_interval_seconds=5.0,
        location_scope="STATION_REEFER",
        measurement_zone="REEFER_YARD",
        default_value="CYCLING",
        state_path="cold_chain.reefer01.compressor_status",
        description="Refrigeration compressor run status (OFF, RUNNING, CYCLING, FAULT)",
        simulation_assumption=True,
    ),
    SensorConfig(
        sensor_id="LOG-REEFER-01-PWR-STATE",
        name="Reefer 01 Electrical Power Supply Feed",
        asset_id="REEFER-01",
        domain=LogisticsDomain.COLD_CHAIN,
        subsystem="cold_chain_r01",
        kind=SensorKind.STATE,
        evidence_level=EvidenceLevel.NOT_PUBLICLY_CONFIRMED,
        physical_quantity=PhysicalQuantity.STATUS,
        unit="status",
        sampling_interval_seconds=10.0,
        location_scope="STATION_REEFER",
        measurement_zone="REEFER_YARD",
        default_value="STATION_GRID",
        state_path="cold_chain.reefer01.power_source",
        description="Power supply source for reefer container (STATION_GRID, DIESEL_GENSET, OFF)",
        simulation_assumption=True,
    ),
    SensorConfig(
        sensor_id="LOG-REEFER-01-EXCURSION",
        name="Reefer 01 Thermal Excursion Indicator",
        asset_id="REEFER-01",
        domain=LogisticsDomain.COLD_CHAIN,
        subsystem="cold_chain_r01",
        kind=SensorKind.DERIVED,
        evidence_level=EvidenceLevel.DERIVED,
        physical_quantity=PhysicalQuantity.BOOLEAN,
        unit="bool",
        sampling_interval_seconds=10.0,
        location_scope="STATION_REEFER",
        measurement_zone="REEFER_YARD",
        default_value=False,
        state_path="cold_chain.reefer01.temperature_excursion",
        state_dependencies=["cold_chain.reefer01.core_temp_c", "cold_chain.reefer01.setpoint_c"],
        description="Evaluated boolean indicator true if temperature exceeds setpoint + tolerance",
    ),
    SensorConfig(
        sensor_id="LOG-REEFER-02-TEMP",
        name="Reefer 02 Chilled Stores Temperature",
        asset_id="REEFER-02",
        domain=LogisticsDomain.COLD_CHAIN,
        subsystem="cold_chain_r02",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.NOT_PUBLICLY_CONFIRMED,
        physical_quantity=PhysicalQuantity.TEMPERATURE,
        unit="degC",
        sampling_interval_seconds=10.0,
        location_scope="STATION_REEFER",
        measurement_zone="REEFER_YARD",
        min_value=-40.0,
        max_value=20.0,
        default_value=3.5,
        state_path="cold_chain.reefer02.core_temp_c",
        description="Internal temperature sensor for chilled fresh vegetables/supplies Reefer 02",
        simulation_assumption=True,
    ),
    SensorConfig(
        sensor_id="LOG-REEFER-02-STATUS",
        name="Reefer 02 Operational State",
        asset_id="REEFER-02",
        domain=LogisticsDomain.COLD_CHAIN,
        subsystem="cold_chain_r02",
        kind=SensorKind.STATE,
        evidence_level=EvidenceLevel.DOCUMENTED,
        physical_quantity=PhysicalQuantity.STATUS,
        unit="status",
        sampling_interval_seconds=10.0,
        location_scope="STATION_REEFER",
        measurement_zone="REEFER_YARD",
        default_value="NORMAL",
        state_path="cold_chain.reefer02.status",
        description="Operational condition of secondary chilled stores container",
    ),

    # --------------------------------------------------------------------------
    # 5. AVIATION LOGISTICS (7 Points)
    # --------------------------------------------------------------------------
    SensorConfig(
        sensor_id="LOG-AV-HELI-STATUS",
        name="Station Helicopter Flight Operations Status",
        asset_id="EXPEDITION_HELICOPTER",
        domain=LogisticsDomain.AVIATION,
        subsystem="aviation_heli",
        kind=SensorKind.STATE,
        evidence_level=EvidenceLevel.DOCUMENTED,
        physical_quantity=PhysicalQuantity.STATUS,
        unit="status",
        sampling_interval_seconds=10.0,
        location_scope="AIR_OPERATION",
        measurement_zone="HELIPAD",
        default_value="GROUNDED_READY",
        state_path="aviation.heli.status",
        description="Operating status of expedition helicopter (GROUNDED_READY, IN_FLIGHT, VESSEL_DECK, MAINTENANCE)",
    ),
    SensorConfig(
        sensor_id="LOG-AV-HELI-AIRBORNE",
        name="Helicopter Airborne Flight State",
        asset_id="EXPEDITION_HELICOPTER",
        domain=LogisticsDomain.AVIATION,
        subsystem="aviation_heli",
        kind=SensorKind.STATE,
        evidence_level=EvidenceLevel.NOT_PUBLICLY_CONFIRMED,
        physical_quantity=PhysicalQuantity.BOOLEAN,
        unit="bool",
        sampling_interval_seconds=1.0,
        location_scope="AIR_OPERATION",
        measurement_zone="AIRSPACE",
        default_value=False,
        state_path="aviation.heli.is_airborne",
        description="Weight-on-wheels squat switch indicating active flight",
        simulation_assumption=True,
    ),
    SensorConfig(
        sensor_id="LOG-AV-HELI-FUEL-PCT",
        name="Helicopter Remaining Fuel Capacity Percentage",
        asset_id="EXPEDITION_HELICOPTER",
        domain=LogisticsDomain.AVIATION,
        subsystem="aviation_heli",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.NOT_PUBLICLY_CONFIRMED,
        physical_quantity=PhysicalQuantity.PERCENT,
        unit="%",
        sampling_interval_seconds=5.0,
        location_scope="AIR_OPERATION",
        measurement_zone="AIRSPACE",
        min_value=0.0,
        max_value=100.0,
        default_value=92.0,
        state_path="aviation.heli.fuel_remaining_percent",
        description="Onboard avionics fuel gauge percentage",
        simulation_assumption=True,
    ),
    SensorConfig(
        sensor_id="LOG-AV-HELI-ALTITUDE",
        name="Helicopter Barometric / Radio Altitude",
        asset_id="EXPEDITION_HELICOPTER",
        domain=LogisticsDomain.AVIATION,
        subsystem="aviation_heli",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.NOT_PUBLICLY_CONFIRMED,
        physical_quantity=PhysicalQuantity.ALTITUDE,
        unit="m",
        sampling_interval_seconds=1.0,
        location_scope="AIR_OPERATION",
        measurement_zone="AIRSPACE",
        min_value=0.0,
        max_value=5000.0,
        default_value=0.0,
        state_path="aviation.heli.altitude_m",
        description="Simulated aircraft altitude above sea level",
        simulation_assumption=True,
    ),
    SensorConfig(
        sensor_id="LOG-AV-HELI-GROUND-SPEED",
        name="Helicopter Ground Speed",
        asset_id="EXPEDITION_HELICOPTER",
        domain=LogisticsDomain.AVIATION,
        subsystem="aviation_heli",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.NOT_PUBLICLY_CONFIRMED,
        physical_quantity=PhysicalQuantity.SPEED,
        unit="km_h",
        sampling_interval_seconds=1.0,
        location_scope="AIR_OPERATION",
        measurement_zone="AIRSPACE",
        min_value=0.0,
        max_value=300.0,
        default_value=0.0,
        state_path="aviation.heli.ground_speed_km_h",
        description="Simulated Doppler/GPS ground speed of helicopter",
        simulation_assumption=True,
    ),
    SensorConfig(
        sensor_id="LOG-AV-HELI-FLIGHT-HRS",
        name="Helicopter Cumulative Airframe Flight Hours",
        asset_id="EXPEDITION_HELICOPTER",
        domain=LogisticsDomain.AVIATION,
        subsystem="aviation_heli",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.NOT_PUBLICLY_CONFIRMED,
        physical_quantity=PhysicalQuantity.TIME,
        unit="h",
        sampling_interval_seconds=60.0,
        location_scope="AIR_OPERATION",
        measurement_zone="AIRSPACE",
        min_value=0.0,
        max_value=10000.0,
        default_value=284.5,
        state_path="aviation.heli.cumulative_flight_hours",
        description="Cumulative flight airframe log hours for maintenance tracking",
        simulation_assumption=True,
    ),
    SensorConfig(
        sensor_id="LOG-AV-HELIPAD-STATUS",
        name="Bharati Helipad Operational Condition",
        asset_id="HELIPAD",
        domain=LogisticsDomain.AVIATION,
        subsystem="aviation_helipad",
        kind=SensorKind.STATE,
        evidence_level=EvidenceLevel.DOCUMENTED,
        physical_quantity=PhysicalQuantity.STATUS,
        unit="status",
        sampling_interval_seconds=10.0,
        location_scope="LOCAL_STATION",
        measurement_zone="HELIPAD",
        default_value="CLEAR_OPEN",
        state_path="aviation.helipad.status",
        description="Ground condition of station helipad (CLEAR_OPEN, SNOW_COVERED, CLOSED_WEATHER)",
    ),

    # --------------------------------------------------------------------------
    # 6. MARINE / VESSEL LOGISTICS (7 Points)
    # --------------------------------------------------------------------------
    SensorConfig(
        sensor_id="LOG-MAR-VESSEL-STATUS",
        name="Expedition Vessel Operating State",
        asset_id="EXPEDITION_VESSEL",
        domain=LogisticsDomain.MARINE,
        subsystem="marine_vessel",
        kind=SensorKind.STATE,
        evidence_level=EvidenceLevel.DOCUMENTED,
        physical_quantity=PhysicalQuantity.STATUS,
        unit="status",
        sampling_interval_seconds=30.0,
        location_scope="MARINE_OPERATION",
        measurement_zone="QUILTY_BAY",
        default_value="AT_ANCHOR",
        state_path="marine.vessel.status",
        description="Chartered ice-class expedition ship status (EN_ROUTE, AT_ANCHOR, BERTHED, DEPARTED)",
    ),
    SensorConfig(
        sensor_id="LOG-MAR-VESSEL-DIST",
        name="Expedition Vessel Distance to Station",
        asset_id="EXPEDITION_VESSEL",
        domain=LogisticsDomain.MARINE,
        subsystem="marine_vessel",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.NOT_PUBLICLY_CONFIRMED,
        physical_quantity=PhysicalQuantity.DISTANCE,
        unit="km",
        sampling_interval_seconds=30.0,
        location_scope="MARINE_OPERATION",
        measurement_zone="QUILTY_BAY",
        min_value=0.0,
        max_value=1000.0,
        default_value=2.4,
        state_path="marine.vessel.distance_to_station_km",
        description="AIS/radar range distance from expedition vessel to Bharati station",
        simulation_assumption=True,
    ),
    SensorConfig(
        sensor_id="LOG-MAR-VESSEL-SPEED",
        name="Expedition Vessel Speed Over Ground",
        asset_id="EXPEDITION_VESSEL",
        domain=LogisticsDomain.MARINE,
        subsystem="marine_vessel",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.NOT_PUBLICLY_CONFIRMED,
        physical_quantity=PhysicalQuantity.SPEED,
        unit="knot",
        sampling_interval_seconds=10.0,
        location_scope="MARINE_OPERATION",
        measurement_zone="QUILTY_BAY",
        min_value=0.0,
        max_value=30.0,
        default_value=0.0,
        state_path="marine.vessel.speed_knots",
        description="AIS vessel speed over ground",
        simulation_assumption=True,
    ),
    SensorConfig(
        sensor_id="LOG-MAR-BARGE-STATUS",
        name="Offloading Barge / Pontoon Status",
        asset_id="BARGE_01",
        domain=LogisticsDomain.MARINE,
        subsystem="marine_barge",
        kind=SensorKind.STATE,
        evidence_level=EvidenceLevel.DOCUMENTED,
        physical_quantity=PhysicalQuantity.STATUS,
        unit="status",
        sampling_interval_seconds=10.0,
        location_scope="MARINE_OPERATION",
        measurement_zone="QUILTY_BAY",
        default_value="STANDBY",
        state_path="marine.barge.status",
        description="Documented motorised offloading barge status (STANDBY, SHUTTLE, DOCKED, SECURED)",
    ),
    SensorConfig(
        sensor_id="LOG-MAR-DISCHARGE-PROGRESS",
        name="Voyage Cargo Discharge Progress",
        asset_id="CARGO_DISCHARGE",
        domain=LogisticsDomain.MARINE,
        subsystem="marine_discharge",
        kind=SensorKind.STATE,
        evidence_level=EvidenceLevel.DOCUMENTED,
        physical_quantity=PhysicalQuantity.PERCENT,
        unit="%",
        sampling_interval_seconds=60.0,
        location_scope="MARINE_OPERATION",
        measurement_zone="QUILTY_BAY",
        min_value=0.0,
        max_value=100.0,
        default_value=45.0,
        state_path="marine.discharge_progress_percent",
        description="Expedition supply unloading completion progress percentage",
    ),
    SensorConfig(
        sensor_id="LOG-MAR-SEA-BERTH-SAFE",
        name="Coastal Sea Berth Safety Assessment",
        asset_id="SEA_BERTH",
        domain=LogisticsDomain.MARINE,
        subsystem="marine_berth",
        kind=SensorKind.DERIVED,
        evidence_level=EvidenceLevel.DERIVED,
        physical_quantity=PhysicalQuantity.STATUS,
        unit="status",
        sampling_interval_seconds=30.0,
        location_scope="MARINE_OPERATION",
        measurement_zone="QUILTY_BAY",
        default_value="SAFE",
        state_path="marine.sea_berth_safety",
        state_dependencies=["marine.vessel.status"],
        description="Derived sea berth docking condition (SAFE, MARGINAL, UNSAFE) based on environment and vessel",
    ),
    SensorConfig(
        sensor_id="LOG-MAR-UNLOAD-RATE",
        name="Cargo Unloading Transfer Throughput",
        asset_id="CARGO_DISCHARGE",
        domain=LogisticsDomain.MARINE,
        subsystem="marine_discharge",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.NOT_PUBLICLY_CONFIRMED,
        physical_quantity=PhysicalQuantity.FLOW_RATE,
        unit="tonne_h",
        sampling_interval_seconds=30.0,
        location_scope="MARINE_OPERATION",
        measurement_zone="QUILTY_BAY",
        min_value=0.0,
        max_value=100.0,
        default_value=8.5,
        state_path="marine.unloading_rate_tonne_h",
        description="Estimated continuous tonnage rate transferred from ship to shore",
        simulation_assumption=True,
    ),

    # --------------------------------------------------------------------------
    # 7. ROUTES & ACCESSIBILITY (8 Points)
    # Note: Snow depth, ice thickness, wind are owned by Environment layer.
    # --------------------------------------------------------------------------
    SensorConfig(
        sensor_id="LOG-ROUTE-STATION-STATUS",
        name="Station Ring Road Operational Status",
        asset_id="ROUTE_STATION_RING",
        domain=LogisticsDomain.ROUTES,
        subsystem="routes_station",
        kind=SensorKind.STATE,
        evidence_level=EvidenceLevel.DOCUMENTED,
        physical_quantity=PhysicalQuantity.STATUS,
        unit="status",
        sampling_interval_seconds=10.0,
        location_scope="FIELD_ROUTE",
        measurement_zone="STATION_PERIMETER",
        default_value="OPEN",
        state_path="routes.station_ring.status",
        description="Operational transit status of main station internal perimeter road",
    ),
    SensorConfig(
        sensor_id="LOG-ROUTE-HELIPAD-STATUS",
        name="Helipad Access Track Status",
        asset_id="ROUTE_HELIPAD_TRACK",
        domain=LogisticsDomain.ROUTES,
        subsystem="routes_helipad",
        kind=SensorKind.STATE,
        evidence_level=EvidenceLevel.DOCUMENTED,
        physical_quantity=PhysicalQuantity.STATUS,
        unit="status",
        sampling_interval_seconds=10.0,
        location_scope="FIELD_ROUTE",
        measurement_zone="HELIPAD",
        default_value="OPEN",
        state_path="routes.helipad_track.status",
        description="Surface viability of track connecting main station building to helipad",
    ),
    SensorConfig(
        sensor_id="LOG-ROUTE-COAST-STATUS",
        name="Coastal Link Track Status",
        asset_id="ROUTE_COASTAL_LINK",
        domain=LogisticsDomain.ROUTES,
        subsystem="routes_coastal",
        kind=SensorKind.STATE,
        evidence_level=EvidenceLevel.DOCUMENTED,
        physical_quantity=PhysicalQuantity.STATUS,
        unit="status",
        sampling_interval_seconds=10.0,
        location_scope="FIELD_ROUTE",
        measurement_zone="COASTAL_ACCESS",
        default_value="OPEN",
        state_path="routes.coastal_link.status",
        description="Transit status of vehicle route from station down to sea-ice/water edge",
    ),
    SensorConfig(
        sensor_id="LOG-ROUTE-FASTICE-STATUS",
        name="Fast-Ice Heavy Sled Route Status",
        asset_id="ROUTE_FAST_ICE",
        domain=LogisticsDomain.ROUTES,
        subsystem="routes_ice",
        kind=SensorKind.STATE,
        evidence_level=EvidenceLevel.DOCUMENTED,
        physical_quantity=PhysicalQuantity.STATUS,
        unit="status",
        sampling_interval_seconds=30.0,
        location_scope="FIELD_ROUTE",
        measurement_zone="FAST_ICE_SHELF",
        default_value="PASSABLE",
        state_path="routes.fast_ice_route.status",
        description="Safety status of over-ice vehicle route (PASSABLE, CAUTION, CLOSED)",
    ),
    SensorConfig(
        sensor_id="LOG-ROUTE-LARSEMANN-STATUS",
        name="Larsemann Hills Inter-Station Corridor Status",
        asset_id="ROUTE_LARSEMANN",
        domain=LogisticsDomain.ROUTES,
        subsystem="routes_interstation",
        kind=SensorKind.STATE,
        evidence_level=EvidenceLevel.DOCUMENTED,
        physical_quantity=PhysicalQuantity.STATUS,
        unit="status",
        sampling_interval_seconds=30.0,
        location_scope="FIELD_ROUTE",
        measurement_zone="LARSEMANN_CORRIDOR",
        default_value="OPEN",
        state_path="routes.larsemann_interstation.status",
        description="Field track status connecting Bharati to Progress / Zhongshan stations",
    ),
    SensorConfig(
        sensor_id="LOG-ROUTE-VIS-LIMIT",
        name="Route Optical Visibility Limitation",
        asset_id="ROUTE_MONITOR",
        domain=LogisticsDomain.ROUTES,
        subsystem="routes_safety",
        kind=SensorKind.DERIVED,
        evidence_level=EvidenceLevel.DERIVED,
        physical_quantity=PhysicalQuantity.STATUS,
        unit="status",
        sampling_interval_seconds=10.0,
        location_scope="FIELD_ROUTE",
        measurement_zone="STATION_PERIMETER",
        default_value="UNRESTRICTED",
        state_path="routes.visibility_condition",
        description="Derived operational transit impact based on ambient optical visibility",
    ),
    SensorConfig(
        sensor_id="LOG-ROUTE-CREVASSE-RISK",
        name="Inland Glacier Crevasse Risk State",
        asset_id="ROUTE_INLAND_GLACIER",
        domain=LogisticsDomain.ROUTES,
        subsystem="routes_safety",
        kind=SensorKind.DERIVED,
        evidence_level=EvidenceLevel.DERIVED,
        physical_quantity=PhysicalQuantity.STATUS,
        unit="status",
        sampling_interval_seconds=60.0,
        location_scope="FIELD_ROUTE",
        measurement_zone="GLACIER_ROUTE",
        default_value="LOW",
        state_path="routes.crevasse_risk",
        description="Derived crevasse hazard indicator for inland ice sheet traverse routes",
    ),
    SensorConfig(
        sensor_id="LOG-ROUTE-SURFACE-TRACTION",
        name="Snow Surface Traction Index",
        asset_id="ROUTE_MONITOR",
        domain=LogisticsDomain.ROUTES,
        subsystem="routes_traction",
        kind=SensorKind.DERIVED,
        evidence_level=EvidenceLevel.DERIVED,
        physical_quantity=PhysicalQuantity.PERCENT,
        unit="%",
        sampling_interval_seconds=10.0,
        location_scope="FIELD_ROUTE",
        measurement_zone="FIELD_TRACK",
        min_value=0.0,
        max_value=100.0,
        default_value=85.0,
        state_path="routes.surface_traction_index",
        description="Evaluated traction coefficient index for tracked vehicle transit",
    ),

    # --------------------------------------------------------------------------
    # 8. MISSIONS & PERSONNEL LOGISTICS (9 Points)
    # Operational team markers: TEAM-FIELD-01, TEAM-FIELD-02 (zero PII)
    # --------------------------------------------------------------------------
    SensorConfig(
        sensor_id="LOG-MISS-ACTIVE-COUNT",
        name="Active Field Missions Count",
        asset_id="MISSION_CONTROL",
        domain=LogisticsDomain.MISSIONS,
        subsystem="missions_coordination",
        kind=SensorKind.STATE,
        evidence_level=EvidenceLevel.DOCUMENTED,
        physical_quantity=PhysicalQuantity.COUNT,
        unit="count",
        sampling_interval_seconds=10.0,
        location_scope="LOCAL_STATION",
        measurement_zone="OPERATIONS_ROOM",
        min_value=0.0,
        max_value=20.0,
        default_value=1.0,
        state_path="missions.active_missions_count",
        description="Number of authorized remote scientific/logistical parties deployed",
    ),
    SensorConfig(
        sensor_id="LOG-MISS-STATION-PAX",
        name="Personnel On-Station Muster Count",
        asset_id="MISSION_CONTROL",
        domain=LogisticsDomain.MISSIONS,
        subsystem="missions_personnel",
        kind=SensorKind.STATE,
        evidence_level=EvidenceLevel.DOCUMENTED,
        physical_quantity=PhysicalQuantity.COUNT,
        unit="count",
        sampling_interval_seconds=60.0,
        location_scope="LOCAL_STATION",
        measurement_zone="MAIN_BUILDING",
        min_value=0.0,
        max_value=100.0,
        default_value=24.0,
        state_path="missions.station_personnel_count",
        description="Muster count of expedition members physically at Bharati station",
    ),
    SensorConfig(
        sensor_id="LOG-MISS-FIELD-PAX",
        name="Personnel in Field Deployments Count",
        asset_id="MISSION_CONTROL",
        domain=LogisticsDomain.MISSIONS,
        subsystem="missions_personnel",
        kind=SensorKind.STATE,
        evidence_level=EvidenceLevel.DOCUMENTED,
        physical_quantity=PhysicalQuantity.COUNT,
        unit="count",
        sampling_interval_seconds=60.0,
        location_scope="REMOTE_FIELD_SITE",
        measurement_zone="FIELD_TRACK",
        min_value=0.0,
        max_value=50.0,
        default_value=3.0,
        state_path="missions.field_personnel_count",
        description="Total members currently deployed in remote field parties",
    ),
    SensorConfig(
        sensor_id="LOG-MISS-TEAM01-STATUS",
        name="Field Team 01 Mission State",
        asset_id="TEAM-FIELD-01",
        domain=LogisticsDomain.MISSIONS,
        subsystem="missions_team01",
        kind=SensorKind.STATE,
        evidence_level=EvidenceLevel.DOCUMENTED,
        physical_quantity=PhysicalQuantity.STATUS,
        unit="status",
        sampling_interval_seconds=10.0,
        location_scope="REMOTE_FIELD_SITE",
        measurement_zone="FIELD_TRACK",
        default_value="IN_PROGRESS",
        state_path="missions.team01.status",
        description="Operational mission status for Team 01 (PREPARING, IN_PROGRESS, RETURNING, COMPLETED)",
    ),
    SensorConfig(
        sensor_id="LOG-MISS-TEAM01-DIST",
        name="Field Team 01 Distance from Station",
        asset_id="TEAM-FIELD-01",
        domain=LogisticsDomain.MISSIONS,
        subsystem="missions_team01",
        kind=SensorKind.INSTRUMENT,
        evidence_level=EvidenceLevel.NOT_PUBLICLY_CONFIRMED,
        physical_quantity=PhysicalQuantity.DISTANCE,
        unit="km",
        sampling_interval_seconds=10.0,
        location_scope="REMOTE_FIELD_SITE",
        measurement_zone="FIELD_TRACK",
        min_value=0.0,
        max_value=200.0,
        default_value=8.5,
        state_path="missions.team01.distance_km",
        description="Simulated satellite beacon radial distance from Bharati",
        simulation_assumption=True,
    ),
    SensorConfig(
        sensor_id="LOG-MISS-TEAM01-RADIO",
        name="Field Team 01 Scheduled Comms Check",
        asset_id="TEAM-FIELD-01",
        domain=LogisticsDomain.MISSIONS,
        subsystem="missions_team01",
        kind=SensorKind.STATE,
        evidence_level=EvidenceLevel.DOCUMENTED,
        physical_quantity=PhysicalQuantity.STATUS,
        unit="status",
        sampling_interval_seconds=30.0,
        location_scope="REMOTE_FIELD_SITE",
        measurement_zone="FIELD_TRACK",
        default_value="ACKNOWLEDGED",
        state_path="missions.team01.radio_check_status",
        description="VHF/HF schedule check-in confirmation (ACKNOWLEDGED, OVERDUE, SILENCE)",
    ),
    SensorConfig(
        sensor_id="LOG-MISS-TEAM01-RETURN-MARGIN",
        name="Field Team 01 Return Margin Time",
        asset_id="TEAM-FIELD-01",
        domain=LogisticsDomain.MISSIONS,
        subsystem="missions_team01",
        kind=SensorKind.DERIVED,
        evidence_level=EvidenceLevel.DERIVED,
        physical_quantity=PhysicalQuantity.TIME,
        unit="min",
        sampling_interval_seconds=10.0,
        location_scope="REMOTE_FIELD_SITE",
        measurement_zone="FIELD_TRACK",
        min_value=-300.0,
        max_value=1440.0,
        default_value=180.0,
        state_path="missions.team01.return_margin_minutes",
        description="Estimated safety margin minutes before weather window or fuel reserves expire",
    ),
    SensorConfig(
        sensor_id="LOG-MISS-TEAM02-STATUS",
        name="Field Team 02 Mission State",
        asset_id="TEAM-FIELD-02",
        domain=LogisticsDomain.MISSIONS,
        subsystem="missions_team02",
        kind=SensorKind.STATE,
        evidence_level=EvidenceLevel.DOCUMENTED,
        physical_quantity=PhysicalQuantity.STATUS,
        unit="status",
        sampling_interval_seconds=10.0,
        location_scope="REMOTE_FIELD_SITE",
        measurement_zone="FIELD_TRACK",
        default_value="STANDBY",
        state_path="missions.team02.status",
        description="Operational mission status for Team 02 (STANDBY, DEPLOYED)",
    ),
    SensorConfig(
        sensor_id="LOG-MISS-READINESS-INDEX",
        name="Field Mission General Readiness Index",
        asset_id="MISSION_CONTROL",
        domain=LogisticsDomain.MISSIONS,
        subsystem="missions_readiness",
        kind=SensorKind.DERIVED,
        evidence_level=EvidenceLevel.DERIVED,
        physical_quantity=PhysicalQuantity.STATUS,
        unit="status",
        sampling_interval_seconds=30.0,
        location_scope="LOCAL_STATION",
        measurement_zone="OPERATIONS_ROOM",
        default_value="OPTIMAL",
        state_path="missions.readiness_status",
        description="Derived mission launch feasibility based on weather, vehicles, and communications",
    ),

    # --------------------------------------------------------------------------
    # 9. INVENTORY & STORES (10 Points)
    # --------------------------------------------------------------------------
    SensorConfig(
        sensor_id="LOG-INV-RATIONS-DAYS",
        name="Station Food Rations Autonomy Days",
        asset_id="INVENTORY_STORES",
        domain=LogisticsDomain.INVENTORY,
        subsystem="inventory_rations",
        kind=SensorKind.STATE,
        evidence_level=EvidenceLevel.DOCUMENTED,
        physical_quantity=PhysicalQuantity.TIME,
        unit="day",
        sampling_interval_seconds=60.0,
        location_scope="STATION_STORAGE",
        measurement_zone="MAIN_BUILDING",
        min_value=0.0,
        max_value=1000.0,
        default_value=420.0,
        state_path="inventory.rations_autonomy_days",
        description="Calculated days of food subsistence remaining based on wintering pax count",
    ),
    SensorConfig(
        sensor_id="LOG-INV-RATIONS-STOCK",
        name="Food Rations Warehouse Stock Level",
        asset_id="INVENTORY_STORES",
        domain=LogisticsDomain.INVENTORY,
        subsystem="inventory_rations",
        kind=SensorKind.STATE,
        evidence_level=EvidenceLevel.DOCUMENTED,
        physical_quantity=PhysicalQuantity.PERCENT,
        unit="%",
        sampling_interval_seconds=60.0,
        location_scope="STATION_STORAGE",
        measurement_zone="MAIN_BUILDING",
        min_value=0.0,
        max_value=100.0,
        default_value=88.0,
        state_path="inventory.rations_stock_percent",
        description="Documented dry and frozen provision stock level relative to full wintering baseline",
    ),
    SensorConfig(
        sensor_id="LOG-INV-MEDICAL-STATUS",
        name="Medical Dispensary Essential Supply State",
        asset_id="MEDICAL_ROOM",
        domain=LogisticsDomain.INVENTORY,
        subsystem="inventory_medical",
        kind=SensorKind.STATE,
        evidence_level=EvidenceLevel.DOCUMENTED,
        physical_quantity=PhysicalQuantity.STATUS,
        unit="status",
        sampling_interval_seconds=60.0,
        location_scope="STATION_STORAGE",
        measurement_zone="MEDICAL_DISPENSARY",
        default_value="STOCKED",
        state_path="inventory.medical_supplies_status",
        description="Audit state of emergency drugs, trauma kits, and surgical reserves",
    ),
    SensorConfig(
        sensor_id="LOG-INV-SPARES-GEN-PCT",
        name="Power Generation Critical Spares Level",
        asset_id="INVENTORY_STORES",
        domain=LogisticsDomain.INVENTORY,
        subsystem="inventory_spares",
        kind=SensorKind.STATE,
        evidence_level=EvidenceLevel.DOCUMENTED,
        physical_quantity=PhysicalQuantity.PERCENT,
        unit="%",
        sampling_interval_seconds=60.0,
        location_scope="STATION_STORAGE",
        measurement_zone="ENERGY_WORKSHOP",
        min_value=0.0,
        max_value=100.0,
        default_value=82.0,
        state_path="inventory.generator_spares_percent",
        description="Critical spare parts inventory for Scania / CHP generator sets",
    ),
    SensorConfig(
        sensor_id="LOG-INV-SPARES-VEH-PCT",
        name="Vehicle & Track Spares Level",
        asset_id="INVENTORY_STORES",
        domain=LogisticsDomain.INVENTORY,
        subsystem="inventory_spares",
        kind=SensorKind.STATE,
        evidence_level=EvidenceLevel.DOCUMENTED,
        physical_quantity=PhysicalQuantity.PERCENT,
        unit="%",
        sampling_interval_seconds=60.0,
        location_scope="STATION_STORAGE",
        measurement_zone="GARAGE",
        min_value=0.0,
        max_value=100.0,
        default_value=75.0,
        state_path="inventory.vehicle_spares_percent",
        description="PistenBully track belts, hydraulic hoses, filters, and track cleats stock",
    ),
    SensorConfig(
        sensor_id="LOG-INV-WATER-TREAT-PCT",
        name="RO Water Treatment Consumables Level",
        asset_id="INVENTORY_STORES",
        domain=LogisticsDomain.INVENTORY,
        subsystem="inventory_consumables",
        kind=SensorKind.STATE,
        evidence_level=EvidenceLevel.DOCUMENTED,
        physical_quantity=PhysicalQuantity.PERCENT,
        unit="%",
        sampling_interval_seconds=60.0,
        location_scope="STATION_STORAGE",
        measurement_zone="WATER_TREATMENT_PLANT",
        min_value=0.0,
        max_value=100.0,
        default_value=90.0,
        state_path="inventory.water_treatment_spares_percent",
        description="Cartridge filters, chlorine tablets, and RO membranes in store",
    ),
    SensorConfig(
        sensor_id="LOG-INV-BATTERY-STORES",
        name="Station Backup Emergency Batteries Count",
        asset_id="INVENTORY_STORES",
        domain=LogisticsDomain.INVENTORY,
        subsystem="inventory_batteries",
        kind=SensorKind.STATE,
        evidence_level=EvidenceLevel.DOCUMENTED,
        physical_quantity=PhysicalQuantity.COUNT,
        unit="count",
        sampling_interval_seconds=60.0,
        location_scope="STATION_STORAGE",
        measurement_zone="ELECTRICAL_ROOM",
        min_value=0.0,
        max_value=500.0,
        default_value=48.0,
        state_path="inventory.emergency_batteries_count",
        description="Charged spare 12V/24V deep-cycle batteries in logistics store",
    ),
    SensorConfig(
        sensor_id="LOG-INV-SAFETY-PPE-PCT",
        name="Extreme Cold Weather PPE Stock Level",
        asset_id="INVENTORY_STORES",
        domain=LogisticsDomain.INVENTORY,
        subsystem="inventory_ppe",
        kind=SensorKind.STATE,
        evidence_level=EvidenceLevel.DOCUMENTED,
        physical_quantity=PhysicalQuantity.PERCENT,
        unit="%",
        sampling_interval_seconds=60.0,
        location_scope="STATION_STORAGE",
        measurement_zone="MAIN_BUILDING",
        min_value=0.0,
        max_value=100.0,
        default_value=95.0,
        state_path="inventory.ppe_gear_percent",
        description="Thermal suits, gloves, goggles, and mountaineering safety kit reserve",
    ),
    SensorConfig(
        sensor_id="LOG-INV-CRITICAL-ALERTS",
        name="Critical Stockout Alerts Count",
        asset_id="INVENTORY_STORES",
        domain=LogisticsDomain.INVENTORY,
        subsystem="inventory_alerts",
        kind=SensorKind.DERIVED,
        evidence_level=EvidenceLevel.DERIVED,
        physical_quantity=PhysicalQuantity.COUNT,
        unit="count",
        sampling_interval_seconds=60.0,
        location_scope="STATION_STORAGE",
        measurement_zone="OPERATIONS_ROOM",
        min_value=0.0,
        max_value=20.0,
        default_value=0.0,
        state_path="inventory.critical_stockout_alerts_count",
        description="Number of critical stock lines currently below wintering threshold (<30%)",
    ),
    SensorConfig(
        sensor_id="LOG-INV-STOCKOUT-RISK",
        name="Composite Inventory Stockout Risk Score",
        asset_id="INVENTORY_STORES",
        domain=LogisticsDomain.INVENTORY,
        subsystem="inventory_risk",
        kind=SensorKind.DERIVED,
        evidence_level=EvidenceLevel.DERIVED,
        physical_quantity=PhysicalQuantity.SCORE,
        unit="score",
        sampling_interval_seconds=60.0,
        location_scope="STATION_STORAGE",
        measurement_zone="OPERATIONS_ROOM",
        min_value=0.0,
        max_value=1.0,
        default_value=0.05,
        state_path="inventory.stockout_risk_score",
        description="Evaluated supply risk score (0.0 = low risk, 1.0 = severe deprivation)",
    ),

    # --------------------------------------------------------------------------
    # 10. WASTE & RETURN LOGISTICS (5 Points)
    # Madrid Protocol on Environmental Protection to the Antarctic Treaty
    # --------------------------------------------------------------------------
    SensorConfig(
        sensor_id="LOG-WASTE-SOLID-VOL",
        name="Compacted Solid Waste Stored Volume",
        asset_id="WASTE_FACILITY",
        domain=LogisticsDomain.WASTE,
        subsystem="waste_solid",
        kind=SensorKind.STATE,
        evidence_level=EvidenceLevel.DOCUMENTED,
        physical_quantity=PhysicalQuantity.VOLUME,
        unit="m3",
        sampling_interval_seconds=60.0,
        location_scope="STATION_STORAGE",
        measurement_zone="WASTE_DISPOSAL_MODULE",
        min_value=0.0,
        max_value=200.0,
        default_value=18.5,
        state_path="waste.solid_waste_volume_m3",
        description="Measured volume of segregated and baled solid non-biodegradable waste",
    ),
    SensorConfig(
        sensor_id="LOG-WASTE-SOLID-PCT",
        name="Solid Waste Staging Capacity Utilisation",
        asset_id="WASTE_FACILITY",
        domain=LogisticsDomain.WASTE,
        subsystem="waste_solid",
        kind=SensorKind.STATE,
        evidence_level=EvidenceLevel.DOCUMENTED,
        physical_quantity=PhysicalQuantity.PERCENT,
        unit="%",
        sampling_interval_seconds=60.0,
        location_scope="STATION_STORAGE",
        measurement_zone="WASTE_DISPOSAL_MODULE",
        min_value=0.0,
        max_value=100.0,
        default_value=32.0,
        state_path="waste.solid_storage_percent",
        description="Percentage of waste container staging volume currently occupied",
    ),
    SensorConfig(
        sensor_id="LOG-WASTE-HAZARD-VOL",
        name="Hazardous Waste Containment Volume",
        asset_id="WASTE_FACILITY",
        domain=LogisticsDomain.WASTE,
        subsystem="waste_hazmat",
        kind=SensorKind.STATE,
        evidence_level=EvidenceLevel.DOCUMENTED,
        physical_quantity=PhysicalQuantity.VOLUME,
        unit="L",
        sampling_interval_seconds=60.0,
        location_scope="STATION_STORAGE",
        measurement_zone="WASTE_DISPOSAL_MODULE",
        min_value=0.0,
        max_value=10000.0,
        default_value=850.0,
        state_path="waste.hazard_waste_volume_l",
        description="Drummed chemical, laboratory, and oil residue volume staged for voyage removal",
    ),
    SensorConfig(
        sensor_id="LOG-WASTE-HAZARD-STATUS",
        name="Hazardous Waste Drum Integrity Status",
        asset_id="WASTE_FACILITY",
        domain=LogisticsDomain.WASTE,
        subsystem="waste_hazmat",
        kind=SensorKind.STATE,
        evidence_level=EvidenceLevel.DOCUMENTED,
        physical_quantity=PhysicalQuantity.STATUS,
        unit="status",
        sampling_interval_seconds=60.0,
        location_scope="STATION_STORAGE",
        measurement_zone="WASTE_DISPOSAL_MODULE",
        default_value="SECURED",
        state_path="waste.hazard_containment_status",
        description="Integrity status of double-bunded hazardous waste drums",
    ),
    SensorConfig(
        sensor_id="LOG-WASTE-RET-READY",
        name="Madrid Protocol Return Shipment Readiness",
        asset_id="WASTE_FACILITY",
        domain=LogisticsDomain.WASTE,
        subsystem="waste_return",
        kind=SensorKind.STATE,
        evidence_level=EvidenceLevel.DOCUMENTED,
        physical_quantity=PhysicalQuantity.PERCENT,
        unit="%",
        sampling_interval_seconds=60.0,
        location_scope="STATION_STORAGE",
        measurement_zone="WASTE_DISPOSAL_MODULE",
        min_value=0.0,
        max_value=100.0,
        default_value=85.0,
        state_path="waste.return_shipment_readiness_percent",
        description="Percentage of returnable waste under the Madrid Protocol fully documented, packaged, and palletized for ship backhaul",
    ),

    # --------------------------------------------------------------------------
    # 11. DERIVED LOGISTICS INDICATORS (8 Points)
    # --------------------------------------------------------------------------
    SensorConfig(
        sensor_id="LOG-DERIVED-FLEET-AVAIL",
        name="Station Fleet Operational Availability",
        asset_id="DERIVED_LOGISTICS_ENGINE",
        domain=LogisticsDomain.DERIVED,
        subsystem="derived_fleet",
        kind=SensorKind.DERIVED,
        evidence_level=EvidenceLevel.DERIVED,
        physical_quantity=PhysicalQuantity.PERCENT,
        unit="%",
        sampling_interval_seconds=10.0,
        location_scope="DERIVED_LOGISTICS_ENGINE",
        measurement_zone="STATION_PERIMETER",
        min_value=0.0,
        max_value=100.0,
        default_value=93.75,
        state_path="derived.fleet_availability_percent",
        state_dependencies=["fleet.pb01.status", "fleet.pb02.status", "fleet.sc01.status"],
        description="Evaluated percentage of station fleet assets operational and ready for mission tasking",
    ),
    SensorConfig(
        sensor_id="LOG-DERIVED-CARGO-INTEGRITY",
        name="Cargo Shock & Environmental Integrity Index",
        asset_id="DERIVED_LOGISTICS_ENGINE",
        domain=LogisticsDomain.DERIVED,
        subsystem="derived_cargo",
        kind=SensorKind.DERIVED,
        evidence_level=EvidenceLevel.DERIVED,
        physical_quantity=PhysicalQuantity.PERCENT,
        unit="%",
        sampling_interval_seconds=10.0,
        location_scope="DERIVED_LOGISTICS_ENGINE",
        measurement_zone="CONTAINER_YARD",
        min_value=0.0,
        max_value=100.0,
        default_value=98.0,
        state_path="derived.cargo_integrity_index",
        state_dependencies=["cargo.c01.shock_g", "cargo.c01.tilt_deg", "cargo.c01.door_status"],
        description="Composite cargo integrity score tracking handling shocks, tilts, and weather seal",
    ),
    SensorConfig(
        sensor_id="LOG-DERIVED-COLD-CHAIN-RISK",
        name="Cold-Chain Compromise Risk Score",
        asset_id="DERIVED_LOGISTICS_ENGINE",
        domain=LogisticsDomain.DERIVED,
        subsystem="derived_cold_chain",
        kind=SensorKind.DERIVED,
        evidence_level=EvidenceLevel.DERIVED,
        physical_quantity=PhysicalQuantity.SCORE,
        unit="score",
        sampling_interval_seconds=10.0,
        location_scope="DERIVED_LOGISTICS_ENGINE",
        measurement_zone="REEFER_YARD",
        min_value=0.0,
        max_value=1.0,
        default_value=0.0,
        state_path="derived.cold_chain_risk_score",
        state_dependencies=["cold_chain.reefer01.core_temp_c", "cold_chain.reefer01.temperature_excursion"],
        description="Probabilistic risk score of frozen food supply degradation",
    ),
    SensorConfig(
        sensor_id="LOG-DERIVED-ROUTE-ACCESS",
        name="Ground Route Network Accessibility",
        asset_id="DERIVED_LOGISTICS_ENGINE",
        domain=LogisticsDomain.DERIVED,
        subsystem="derived_routes",
        kind=SensorKind.DERIVED,
        evidence_level=EvidenceLevel.DERIVED,
        physical_quantity=PhysicalQuantity.PERCENT,
        unit="%",
        sampling_interval_seconds=10.0,
        location_scope="DERIVED_LOGISTICS_ENGINE",
        measurement_zone="FIELD_TRACK",
        min_value=0.0,
        max_value=100.0,
        default_value=100.0,
        state_path="derived.ground_route_accessibility_percent",
        state_dependencies=["routes.station_ring.status", "routes.helipad_track.status", "routes.coastal_link.status"],
        description="Percentage of ground route network currently passable for tracked transport",
    ),
    SensorConfig(
        sensor_id="LOG-DERIVED-AIR-ACCESS",
        name="Aviation Operation Accessibility",
        asset_id="DERIVED_LOGISTICS_ENGINE",
        domain=LogisticsDomain.DERIVED,
        subsystem="derived_aviation",
        kind=SensorKind.DERIVED,
        evidence_level=EvidenceLevel.DERIVED,
        physical_quantity=PhysicalQuantity.PERCENT,
        unit="%",
        sampling_interval_seconds=10.0,
        location_scope="DERIVED_LOGISTICS_ENGINE",
        measurement_zone="HELIPAD",
        min_value=0.0,
        max_value=100.0,
        default_value=100.0,
        state_path="derived.aviation_accessibility_percent",
        state_dependencies=["aviation.helipad.status", "aviation.heli.status"],
        description="Evaluated flight operational feasibility score based on helipad and environment",
    ),
    SensorConfig(
        sensor_id="LOG-DERIVED-MARINE-ACCESS",
        name="Marine Coastal Offloading Accessibility",
        asset_id="DERIVED_LOGISTICS_ENGINE",
        domain=LogisticsDomain.DERIVED,
        subsystem="derived_marine",
        kind=SensorKind.DERIVED,
        evidence_level=EvidenceLevel.DERIVED,
        physical_quantity=PhysicalQuantity.PERCENT,
        unit="%",
        sampling_interval_seconds=10.0,
        location_scope="DERIVED_LOGISTICS_ENGINE",
        measurement_zone="QUILTY_BAY",
        min_value=0.0,
        max_value=100.0,
        default_value=85.0,
        state_path="derived.marine_accessibility_percent",
        state_dependencies=["marine.sea_berth_safety", "marine.vessel.status"],
        description="Feasibility score of boat and barge sea-to-shore cargo transfers",
    ),
    SensorConfig(
        sensor_id="LOG-DERIVED-LOGISTICS-RISK",
        name="Composite Station Logistics Risk Score",
        asset_id="DERIVED_LOGISTICS_ENGINE",
        domain=LogisticsDomain.DERIVED,
        subsystem="derived_risk",
        kind=SensorKind.DERIVED,
        evidence_level=EvidenceLevel.DERIVED,
        physical_quantity=PhysicalQuantity.SCORE,
        unit="score",
        sampling_interval_seconds=10.0,
        location_scope="DERIVED_LOGISTICS_ENGINE",
        measurement_zone="OPERATIONS_ROOM",
        min_value=0.0,
        max_value=1.0,
        default_value=0.05,
        state_path="derived.composite_logistics_risk",
        description="Normalized composite risk across fleet, cargo, fuel, route, and cold-chain subsystems",
    ),
    SensorConfig(
        sensor_id="LOG-DERIVED-LOGISTICS-CONDITION",
        name="Station Logistics Explainable Operating Condition",
        asset_id="DERIVED_LOGISTICS_ENGINE",
        domain=LogisticsDomain.DERIVED,
        subsystem="derived_condition",
        kind=SensorKind.STATE,
        evidence_level=EvidenceLevel.DERIVED,
        physical_quantity=PhysicalQuantity.STATUS,
        unit="status",
        sampling_interval_seconds=10.0,
        location_scope="DERIVED_LOGISTICS_ENGINE",
        measurement_zone="OPERATIONS_ROOM",
        default_value="NORMAL",
        state_path="derived.logistics_condition_summary",
        description="Explainable operational condition summary: NORMAL, CAUTION, RESTRICTED, or LOCKDOWN",
    ),
]


# Lookup dictionaries for fast access
CONFIG_BY_ID: dict[str, SensorConfig] = {cfg.sensor_id: cfg for cfg in BHARATI_LOGISTICS_SENSORS}
CONFIGS_BY_DOMAIN: dict[LogisticsDomain, list[SensorConfig]] = {}
for cfg in BHARATI_LOGISTICS_SENSORS:
    CONFIGS_BY_DOMAIN.setdefault(cfg.domain, []).append(cfg)


def validate_catalogue() -> None:
    """Validate catalogue invariants: count, uniqueness, units, schemas."""
    total_count = len(BHARATI_LOGISTICS_SENSORS)
    if total_count != 98:
        raise ValueError(f"Expected exactly 98 sensors in catalogue, found {total_count}")

    seen_ids = set()
    for cfg in BHARATI_LOGISTICS_SENSORS:
        if cfg.sensor_id in seen_ids:
            raise ValueError(f"Duplicate sensor_id found: {cfg.sensor_id}")
        seen_ids.add(cfg.sensor_id)

        # Enforce derived typing rule
        if cfg.domain == LogisticsDomain.DERIVED and cfg.sensor_id != "LOG-DERIVED-LOGISTICS-CONDITION":
            if cfg.kind != SensorKind.DERIVED:
                raise ValueError(
                    f"Derived domain sensor {cfg.sensor_id} must have kind SensorKind.DERIVED, got {cfg.kind}"
                )

        # Enforce state vs instrument typing
        if cfg.kind == SensorKind.INSTRUMENT and cfg.physical_quantity == PhysicalQuantity.STATUS:
            raise ValueError(f"Status sensor {cfg.sensor_id} cannot have kind INSTRUMENT")

    # Domain count assertions
    domain_counts = {dom: len(configs) for dom, configs in CONFIGS_BY_DOMAIN.items()}
    expected_domain_counts = {
        LogisticsDomain.FLEET: 16,
        LogisticsDomain.CARGO: 10,
        LogisticsDomain.FUEL: 10,
        LogisticsDomain.COLD_CHAIN: 8,
        LogisticsDomain.AVIATION: 7,
        LogisticsDomain.MARINE: 7,
        LogisticsDomain.ROUTES: 8,
        LogisticsDomain.MISSIONS: 9,
        LogisticsDomain.INVENTORY: 10,
        LogisticsDomain.WASTE: 5,
        LogisticsDomain.DERIVED: 8,
    }
    for dom, expected in expected_domain_counts.items():
        actual = domain_counts.get(dom, 0)
        if actual != expected:
            raise ValueError(f"Domain {dom} expected {expected} points, got {actual}")


# Validate on import
validate_catalogue()
